[Team-05 / BE] API 기본기능 구현
codesquad-members-2021/airbnb pull request #17
Opened 2021-05-22 13:15 UTC by kjk402

안녕하세요 Team-05의 BE 부분을 맡은 Bat입니다.

front와 iOS 에서 개발하는 데 필요한 API 기능들을 빠르게 구현, 배포 하느라 예외처리 및 코드가 깔끔하지 못합니다. 죄송합니다. 

하기와 같이 airbnb api 기능 구현하여 pull request 드립니다.
(방 데이터는 테스트 용으로 인천에만 두개 생성하였습니다.)

• airbnb summary
=====================================
• 배포 URL : http://52.78.158.138:8080/swagger-ui.html#/ 

• 구현한 기능 
1. 도시목록 보기 : 원래는 도시 목록들과 도시별 이미지만 반환 예정이었으나 도시목록 볼 때 메인페이지의 사진들도 같이 볼 수 있게 해달라고 요청주셔서 다른 사진들도 포함되어있습니다. (메인페이지 이미지들은 현재 DB에 없고 하드코딩 상태입니다. 추후 추가되는 이미지들과 취합하여 DB에 올리도록 하겠습니다. )

2. 방 상세보기

3.  예약 가능한 방들의 평균가격과 가격들 반환

4. 입력한 조건에 맞는 방들 보여주기 (유저가 원하는 조건만 입력 후 검색하기 위해 도시, 기간, 가격, 인원 조건들을 분리 시켰습니다. 
입력한 조건들의 교집합으로 방들을 반환합니다. 입력한 기간에 따라 금액을 계산하여 Receipt DTO에 담습니다.)

5. 방 예약하기 (방 예약 시 해당하는 방이 입력한 조건에 예약이 불가능할 시에 badRequest 리턴합니다.)

6. 예약 취소하기

==============================

• 질문 사항 
1. 추후 구현 예정인 유저가 조건을 null 값으로 입력했을 때 백엔드에서는 조건을 default값으로 검색하도록 상수 선언을 하였습니다. 조건 값이 없다면 default값을 사용하여  검색하는 것이 맞을 지, 바로 모든 값을 반환하는 것이 맞을 지 궁금합니다.

2. Receipt 계산 시에 사용되는 각 요금별 퍼센트도 DB에 담고 사용하는 것이 좋을까요? 그리고 DTO내에서 데이터 계산을 해도 되는 지 역시 궁금합니다.

감사합니다.

2021-05-23 05:54 UTC, MJbae commented on backend/src/main/java/com/example/airbnb/controller/ReservationController.java
>                                @ApiParam(value = "체크인 날짜", example = "2021-05-20") @DateTimeFormat(pattern = "yyyy-MM-dd") @RequestParam LocalDate checkIn,
오! 이렇게 날짜에 대해서 원하는 형식으로 request param으로  받을 수도 있군요! 바로 적용해 봐야겠네요~

2021-05-23 05:54 UTC, MJbae commented on backend/src/main/java/com/example/airbnb/dao/RoomDAO.java
> +        String sql = "SELECT r.room FROM reservation r WHERE (r.check_in BETWEEN :reserve_check_in AND :reserve_check_out) OR" +
SQL 쿼리로 날짜 조건에 따라 조회하는 부분에서 힘들었는데 여기서 인사이트를 얻었네요~ 참고할게요~

2021-05-23 11:47 UTC, kjk402 commented on backend/src/main/java/com/example/airbnb/dao/RoomDAO.java
> +        String sql = "SELECT r.room FROM reservation r WHERE (r.check_in BETWEEN :reserve_check_in AND :reserve_check_out) OR" +
BETWEEN 뿐만 아니라 (r.check_in <= :reserve_check_in) 처럼 부등호도 사용 가능합니다.

2021-05-23 14:15 UTC, ksundong requested changes
안녕하세요! Bat! 리뷰어 Dion입니다.
예외처리는 아무리 바쁘더라도, NPE를 직접 리턴하는 방향은 좋지 못한 것 같습니다.

> 추후 구현 예정인 유저가 조건을 null 값으로 입력했을 때 백엔드에서는 조건을 default값으로 검색하도록 상수 선언을 하였습니다. 조건 값이 없다면 default값을 사용하여 검색하는 것이 맞을 지, 바로 모든 값을 반환하는 것이 맞을 지 궁금합니다.

정하기 나름이겠죠. 기본값이 null 이냐, default냐는 정답이 없는 문제입니다.
회사에서라면 기획자분들이 정해주시겠죠? 팀원분들하고 의논해보시기 바랍니다.

> Receipt 계산 시에 사용되는 각 요금별 퍼센트도 DB에 담고 사용하는 것이 좋을까요? 그리고 DTO내에서 데이터 계산을 해도 되는 지 역시 궁금합니다.

DB에 담고 사용하면 어떤 장점과 단점이 있을까요? 한 번 생각해보세요.
DTO 내에서 얼마든지 계산할 수 있습니다. 다만, DTO의 책임일지, Domain의 책임일지는 직접 판단하셔야 합니다. 단순 출력에만 영향을 미친다면, DTO에서 해주는게 낫겠죠.
그리고, DTO에서 계산해주는 것 까지는 좋은데, 생성자에서 데이터의 변경이나 이런 것을 시도하기 보다는 생성자는 인스턴스 생성의 책임을 진다는 것에 중심을 두고 생각해보시면 좋을 것 같습니다.

코멘트를 많이 남겨서 리뷰 피드백을 정리해서 드리진 않을 것 같아요.
리뷰 받은 내용 찬찬히 살펴보시고, 반영해보시면 좋을 것 같아요.
정답을 찾으려고 노력하기 보다는, 어떤 것이 최선일지 항상 생각해보세요.

고생하셨습니다. 수정하시고 다시 리뷰요청 해주시면, 머지하겠습니다.
궁금하시거나 도움이 필요한 부분은 언제든 코멘트 남겨주세요.

2021-05-23 14:15 UTC, ksundong commented on backend/HELP.md
> +# Getting Started
이 파일은 start.spring.io에서 생성해보시면 아시겠지만, gitignore에 추가되어있습니다.

2021-05-23 14:15 UTC, ksundong commented on backend/README.md
> +}
\```json
\```
과 같은 형태로 json 형식을 지정해줄 수 있습니다.

2021-05-23 14:15 UTC, ksundong commented on backend/README.md
> +- [POST] /reservation
reservations가 맞지 않을까요?

2021-05-23 14:15 UTC, ksundong commented on backend/docker/db/conf/custom.cnf
> +collation-server = utf8_unicode_ci
mysql charset과 collation에 대해서 학습해보세요.
mysql에서 utf8은 몇 byte로 저장될까요?
collation이 의미하는 바는 무엇일까요?

2021-05-23 14:15 UTC, ksundong commented on backend/docker/docker-clear.sh
> +# kill -kill `lsof -t -i tcp:3306`
맨 첫 줄에 무엇인가 누락되었네요
sha bang에 대해서 학습해봅시다.

2021-05-23 14:15 UTC, ksundong commented on backend/docker/docker-clear.sh
> +docker stop $(docker ps -aq) ;
semi-colon은 필수는 아닙니다.

2021-05-23 14:15 UTC, ksundong commented on backend/src/main/java/com/example/airbnb/config/WebConfig.java
> +public class WebConfig implements WebMvcConfigurer {
왠만하면 Swagger 설정은 WebConfig와 분리시켜주세요.

2021-05-23 14:15 UTC, ksundong commented on backend/src/main/java/com/example/airbnb/controller/CityController.java
> +    @ResponseStatus(HttpStatus.OK)
왜 적어주셨는지 궁금하네요.
암묵적으로 200응답이거든요.

2021-05-23 14:15 UTC, ksundong commented on backend/src/main/java/com/example/airbnb/controller/ReservationController.java
> +    private ReservationService reservationService;
여기는 왜 final을 사용하지 않으셨는지 궁금하네요.

2021-05-23 14:15 UTC, ksundong commented on backend/src/main/java/com/example/airbnb/controller/ReservationController.java
> +    @ResponseStatus(HttpStatus.CREATED)
👍

2021-05-23 14:15 UTC, ksundong commented on backend/src/main/java/com/example/airbnb/controller/ReservationController.java
> +    public Object reserveRoom(@ApiParam(value = "방 식별자", example = "2") @PathVariable Long roomId,
절대 Object 리턴은 하지 말아주세요.

2021-05-23 14:15 UTC, ksundong commented on backend/src/main/java/com/example/airbnb/controller/ReservationController.java
> +                              @ApiParam(value = "인원", example = "3") @RequestParam int numOfPeople) {
파라미터가 너무 많죠?
DTO로 Wrapping하면 어떨까요?

2021-05-23 14:15 UTC, ksundong commented on backend/src/main/java/com/example/airbnb/controller/ReservationController.java
> +        }
이것이 Controller의 책임일까요?

2021-05-23 14:15 UTC, ksundong commented on backend/src/main/java/com/example/airbnb/controller/ReservationController.java
> +        }
reservationRoom에서 처리해주는건 어떨까요?

2021-05-23 14:15 UTC, ksundong commented on backend/src/main/java/com/example/airbnb/controller/ReservationController.java
> +    @ResponseStatus(HttpStatus.ACCEPTED)
202응답은 Async할 때 보통 사용합니다.
Async한가요? 사실 202여도 상관없습니다.

2021-05-23 14:15 UTC, ksundong commented on backend/src/main/java/com/example/airbnb/controller/RoomController.java
> +                                 @ApiParam(value = "체크아웃 날짜", example = "2021-05-25") @DateTimeFormat(pattern = "yyyy-MM-dd") @RequestParam LocalDate checkOut,
라인이 너무 기네요 😭

2021-05-23 14:15 UTC, ksundong commented on backend/src/main/java/com/example/airbnb/controller/RoomController.java
> +    @GetMapping("/search")
search라는 것이 들어가야 했을 지 고민해주세요.

2021-05-23 14:15 UTC, ksundong commented on backend/src/main/java/com/example/airbnb/dao/CityDAO.java
> +    private final NamedParameterJdbcTemplate namedParameterJdbcTemplate;
둘 다 사용해주시는 이유는 무엇인가요?

2021-05-23 14:15 UTC, ksundong commented on backend/src/main/java/com/example/airbnb/dao/CityDAO.java
> +        });
매 요청마다 mapper가 생길것이고, 왜 null을 리턴해주시는지 잘 모르겠네요.

2021-05-23 14:15 UTC, ksundong commented on backend/src/main/java/com/example/airbnb/dao/CityDAO.java
> +        String sql = "SELECT c.id, c.city_name, c.city_image FROM city c ORDER BY c.id";
쿼리를 어떻게 관리하면 좋을까요?
그리고 왠만하면 WHERE 조건은 포함해주시거나, 아니면 LIMIT을 걸어주시는걸 추천드려요.
페이징도 도전해보시면 좋을 것 같네요.

2021-05-23 14:15 UTC, ksundong commented on backend/src/main/java/com/example/airbnb/dao/ReservationDAO.java
> +        return keyHolder.getKey().longValue();
👍

2021-05-23 14:15 UTC, ksundong commented on backend/src/main/java/com/example/airbnb/dao/ReservationDAO.java
> +
이렇게 빈 라인을 많이 커밋할 필욘 없겠죠.

2021-05-23 14:15 UTC, ksundong commented on backend/src/main/java/com/example/airbnb/dao/RoomDAO.java
> +        return Optional.ofNullable(DataAccessUtils.singleResult(roomDTO));
그냥 `stream().findFirst()`를 써줘도 될 것 같네요.

2021-05-23 14:15 UTC, ksundong commented on backend/src/main/java/com/example/airbnb/dao/RoomDAO.java
> +        }
n번 쿼리를 날리는 구조 같은데, 최선인가요?

2021-05-23 14:15 UTC, ksundong commented on backend/src/main/java/com/example/airbnb/domain/Reservation.java
> +    private final Long room;
필드가 너무 많은건 아닌지 생각해봅시다.

2021-05-23 14:15 UTC, ksundong commented on backend/src/main/java/com/example/airbnb/dto/Receipt.java
> +    }
로직을 메서드로 분리해보세요.

2021-05-23 14:15 UTC, ksundong commented on backend/src/main/java/com/example/airbnb/dto/RoomListDTO.java
> +    private Receipt receipt;
RoomLIst인데, room 하나인 것 같네요.

2021-05-23 14:15 UTC, ksundong commented on backend/src/main/java/com/example/airbnb/service/ReservationService.java
> +        RoomDTO roomDTO = roomDAO.getRoom(roomId).orElseThrow(() -> new NullPointerException("해당하는 방이 없습니다."));
NPE는 직접 리턴하지 말아주세요...

2021-05-23 14:15 UTC, ksundong commented on backend/src/main/java/com/example/airbnb/service/ReservationService.java
> +        Long reservationId = reservationDAO.reservationRoom(roomId, checkIn, checkOut, guestCount, totalPrice);
절차적으로 작성해주신 이유가 있나요?

2021-05-23 14:15 UTC, ksundong commented on backend/src/main/java/com/example/airbnb/service/ReservationService.java
> +        Long reservationId = reservationDAO.reservationRoom(roomId, checkIn, checkOut, guestCount, totalPrice);
또, Controller에서 검증이 되었음을 알기 때문에 구조적으로 결합도가 생겨버렸습니다.

2021-05-23 14:15 UTC, ksundong commented on backend/src/main/java/com/example/airbnb/service/RoomService.java
> +    private static final LocalDate DEFAULT_CHECK_OUT = LocalDate.parse("2100-01-01");
기본 값을 여기서 관리할 이유는 없어보이네요.

2021-05-23 14:15 UTC, ksundong commented on backend/src/main/java/com/example/airbnb/service/RoomService.java
> +    private static final int DEFAULT_MAX_GUEST = 9999;
여기도 마찬가지입니다.

2021-05-23 14:15 UTC, ksundong commented on backend/src/main/java/com/example/airbnb/service/RoomService.java
> +                locationDAO.getLocationByLocationId(id).orElseThrow(() -> new NullPointerException("해당하는 로케이션이 없습니다.")),
한 쿼리로 불러오는게 어떨까요?

2021-05-23 14:15 UTC, ksundong commented on backend/src/main/java/com/example/airbnb/service/RoomService.java
> +    }
이건 stream 쓰시면 간단히 해결될 것 같네요.

2021-05-23 14:15 UTC, ksundong commented on backend/src/main/java/com/example/airbnb/service/RoomService.java
> +    }
과연이게 Service에 있어야하는지 궁금해요.

2021-05-24 02:56 UTC, kjk402 commented on backend/docker/db/conf/custom.cnf
> +collation-server = utf8_unicode_ci
charset은 어떤 문자로 db에 저장될 지 인코딩 방식을 지정하는 것이고,
collation은 저장된 값들을 비교, 정렬할 때 사용되는 규칙들의 집합을 의미합니다.

utf8가 문자를 저장할 때 사용하는 바이트는 가변 4바이트이나, mysql에서는 가변 3바이트 입니다. 
(mysql에서는 가변 4바이트까지 저장할 수 있는 utf8mb4가 별도로 존재합니다.)

2021-05-24 02:57 UTC, kjk402 commented on backend/README.md
> +}
오! 형식을 지정해줄 수 있네요.

감사합니다.

2021-05-24 03:02 UTC, kjk402 commented on backend/docker/docker-clear.sh
> +# kill -kill `lsof -t -i tcp:3306`
느낌표가 누락되었습니다. 
스크립트의 맨처음에 셔뱅(#!) 이란게 위치해야 하네요.

감사합니다.

2021-05-24 03:08 UTC, kjk402 commented on backend/src/main/java/com/example/airbnb/controller/CityController.java
> +    @ResponseStatus(HttpStatus.OK)
HTTP Status의 기본값이 200이지만 명시적으로 나타내고자 표기하였습니다.
200들은 삭제하였습니다.!

2021-05-24 08:24 UTC, kjk402 commented on backend/src/main/java/com/example/airbnb/service/RoomService.java
> +                locationDAO.getLocationByLocationId(id).orElseThrow(() -> new NullPointerException("해당하는 로케이션이 없습니다.")),
SELECT_ROOM_BY_ID 쿼리 한개로 불러오도록 수정하였습니다.

2021-05-24 08:25 UTC, kjk402 commented on backend/src/main/java/com/example/airbnb/service/RoomService.java
> +    }
스트림 사용하게 바꿨습니다.~

2021-05-24 08:26 UTC, kjk402 commented on backend/src/main/java/com/example/airbnb/service/RoomService.java
> +    }
Service에서 사용되는 계산 로직들 utils로 분리시켰습니다.

2021-05-24 08:28 UTC, kjk402 commented on backend/src/main/java/com/example/airbnb/service/RoomService.java
> +    private static final LocalDate DEFAULT_CHECK_OUT = LocalDate.parse("2100-01-01");
네 제거하였습니다.

2021-05-24 08:28 UTC, kjk402 commented on backend/src/main/java/com/example/airbnb/config/WebConfig.java
> +public class WebConfig implements WebMvcConfigurer {
분리시켰습니다.~

2021-05-24 08:29 UTC, kjk402 commented on backend/src/main/java/com/example/airbnb/controller/ReservationController.java
> +    private ReservationService reservationService;
여기만 까먹은 듯합니다. ㅠㅠ
final 추가하였습니다.

2021-05-24 08:30 UTC, kjk402 commented on backend/src/main/java/com/example/airbnb/controller/ReservationController.java
> +    public Object reserveRoom(@ApiParam(value = "방 식별자", example = "2") @PathVariable Long roomId,
네. DTO를 리턴하게 수정하였으며 badRequest 부분은 예외처리로 변경하였습니다.

2021-05-24 08:30 UTC, kjk402 commented on backend/src/main/java/com/example/airbnb/controller/ReservationController.java
> +        }
서비스에서 예외처리 하게 변경하였습니다. ^^

2021-05-24 08:32 UTC, kjk402 commented on backend/src/main/java/com/example/airbnb/dao/CityDAO.java
> +    private final NamedParameterJdbcTemplate namedParameterJdbcTemplate;
처음엔 jdbcTemplate으로 개발하다 이후에 named로 변경하는 도중에 삭제를 안한 것같습니다.
named로만 사용토록 수정하였습니다.

2021-05-24 08:33 UTC, kjk402 commented on backend/src/main/java/com/example/airbnb/dao/CityDAO.java
> +        String sql = "SELECT c.id, c.city_name, c.city_image FROM city c ORDER BY c.id";
코틀린으로 한곳에서 관리하도록 변경하였습니다.

2021-05-24 08:34 UTC, kjk402 commented on backend/src/main/java/com/example/airbnb/dao/CityDAO.java
> +        String sql = "SELECT c.id, c.city_name, c.city_image FROM city c ORDER BY c.id";
LIMIT 도 추가해줬습니다.~

2021-05-24 08:35 UTC, kjk402 commented on backend/src/main/java/com/example/airbnb/dao/ReservationDAO.java
> +
죄송합니다. 커밋, 푸시할 때 확인하고 올리도록 하겠습니다.
빈 라인 제거하였습니다.

2021-05-24 08:36 UTC, kjk402 commented on backend/src/main/java/com/example/airbnb/dao/RoomDAO.java
> +        return Optional.ofNullable(DataAccessUtils.singleResult(roomDTO));
Optional로만 리턴해 줄려고 했는데 좋은 기능이 있었군요.

감사합니다.

2021-05-24 08:37 UTC, kjk402 commented on backend/src/main/java/com/example/airbnb/dao/RoomDAO.java
> +        }
조건절 리스트로 검색가능한 IN으로 변경하였습니다.

2021-05-24 08:38 UTC, kjk402 commented on backend/src/main/java/com/example/airbnb/domain/Reservation.java
> +    private final Long room;
쓰이지 않는 필드들 수정, 제거하였습니다.!

2021-05-24 08:39 UTC, kjk402 commented on backend/src/main/java/com/example/airbnb/dto/Receipt.java
> +    }
메서드 분리, 퍼센트 상수 선언하였습니다.

2021-05-24 08:39 UTC, kjk402 commented on backend/src/main/java/com/example/airbnb/service/ReservationService.java
> +        RoomDTO roomDTO = roomDAO.getRoom(roomId).orElseThrow(() -> new NullPointerException("해당하는 방이 없습니다."));
네 알겠습니다. NPE 사용하지 않겠습니다.

2021-05-24 09:04 UTC, kjk402 commented on backend/src/main/java/com/example/airbnb/service/ReservationService.java
> +        Long reservationId = reservationDAO.reservationRoom(roomId, checkIn, checkOut, guestCount, totalPrice);
예약 정보에 총가격을 넣는데 입력받은 기간으로 계산 후 DB에 삽입하여 절차적인 것 같습니다.

2021-05-24 09:06 UTC, kjk402 commented on backend/src/main/java/com/example/airbnb/dto/RoomListDTO.java
> +    private Receipt receipt;
조건에 맞는 방들을 보여주기 위해 RoomListDTO라고 명하고 
이를 다시 List 형식인 List<RoomListDTO>로 반환합니다. 
그럼 이름을 수정해야 할까요?

2021-05-24 09:06 UTC, kjk402 commented on backend/README.md
> +- [POST] /reservation
넵 reservations으로 수정하였습니다.

2021-05-24 09:16 UTC, kjk402 commented
안녕하세요 Dion. Bat입니다.

리뷰를 받고 수정을 하니 코드가 훨씬 깔끔해진 것 같습니다. 좋은 리뷰 늘 감사합니다.

대부분의 리뷰주신 부분들에 대해서는 수정하였으나 RequestParam 부분은 아직 수정하지 못하였습니다. (이 부분은 팀원분들과 상의도 하고, 어떤 방법이 더 좋은 지 공부한 후 수정해보겠습니다.)


감사합니다.

2021-05-24 09:23 UTC, kjk402 commented on backend/HELP.md
> +# Getting Started
이전에 쓰던 gitignore 복붙해서 HELP.md 이 빠져있네요. 수정하겠습니다.~

2021-05-25 12:08 UTC, ksundong commented on backend/docker/db/conf/custom.cnf
> +collation-server = utf8_unicode_ci
네 그리고 최근에는 uff8의 사용을 권장하지 않는 추세기도 합니다.

2021-05-25 12:09 UTC, ksundong commented on backend/docker/docker-clear.sh
> +# kill -kill `lsof -t -i tcp:3306`
앗 그 다음에 어떤 것으로 실행할 것인지도 포함해주셔야 합니다.

2021-05-25 12:11 UTC, ksundong commented on backend/src/main/java/com/example/airbnb/dto/RoomListDTO.java
> +    private Receipt receipt;
네 Room~DTO정도가 맞을 것 같고, List를 포장하는 DTO를 선언해주시는게 좋을 것 같아요.

2021-05-25 12:14 UTC, kjk402 commented on backend/src/main/java/com/example/airbnb/dto/RoomListDTO.java
> +    private Receipt receipt;
넵 알겠습니다. 감사합니다. ^^

2021-05-25 12:32 UTC, ksundong approved these changes
안녕하세요! Bat! 피드백 반영해주시느라 대단히 수고 많으셨습니다.
추가적으로 코멘트 남겨드리니 확인해주세요.
고생하셨습니다~

2021-05-25 12:32 UTC, ksundong commented on backend/build.gradle
> +	id 'org.jetbrains.kotlin.jvm' version '1.4.32'
저도 코틀린에 대해서 잘 몰라서 ㅎㅎ..
@wheejuni 한 말씀 부탁드립니다.

2021-05-25 12:32 UTC, ksundong commented on backend/src/main/java/com/example/airbnb/config/WebConfig.java
> +@EnableSwagger2
아직 여기는 안빠졌네요~

2021-05-25 12:32 UTC, ksundong commented on backend/src/main/java/com/example/airbnb/controller/RoomController.java
> +                                    @ApiParam(value = "인원", example = "2") @RequestParam int numOfPeople) {
파라미터를 객체로 받으면 좀 더 깔끔해질 것 같아요.

2021-05-25 12:32 UTC, ksundong commented on backend/src/main/java/com/example/airbnb/dao/CityDAO.java
> +        });
RowMapper는 작성해주신 람다식입니다. 재사용할 수 있도록 하는게 좋을 것 같아요!

2021-05-25 12:32 UTC, ksundong commented on backend/src/main/java/com/example/airbnb/dto/Receipt.java
> +    private static final int CLEANING_FEE = 20000;
상수 추출 좋습니다. 👍

2021-05-25 12:32 UTC, ksundong commented on backend/src/main/java/com/example/airbnb/dto/Receipt.java
> +        if (days > 6) {
6은 무엇일까요? 상수로 빼봅시다.

2021-05-25 12:32 UTC, ksundong commented on backend/src/main/java/com/example/airbnb/service/ReservationService.java
> +        }
저는 이런 if문 각각을 validate~와 같은 메서드로 추출해줍니다.
그리고, validate를 객체에서 해볼수는 없을까? 까지 고민해주고 있어요.

2021-05-25 12:32 UTC, ksundong commented on backend/src/main/java/com/example/airbnb/service/RoomService.java
> +    }
동적쿼리 꼭 도전해보시길 바랍니다!

2021-05-25 12:32 UTC, ksundong commented on backend/src/main/java/com/example/airbnb/service/RoomService.java
> +    }
mysql function은 잘 쓰는지는 모르겠어요. 아니면 그걸로라도 도전을 해보시는걸 추천해보겠습니다.

2021-05-25 12:32 UTC, ksundong commented on backend/src/main/java/com/example/airbnb/utils/Calculators.java
> +    }
위에있는 것과 좀 성격이 다른 것 같아요.
집합에 관련된거 아닌가요?

2021-05-25 12:32 UTC, ksundong commented on backend/src/main/java/com/example/airbnb/utils/Calculators.java
> +    }
스트림을 꼭 활용해보시길 바랍니다.

2021-05-25 12:32 UTC, ksundong commented on backend/src/main/java/com/example/airbnb/utils/Calculators.java
> +public class Calculators {
항상 Utility성 클래스는 private 기본생성자를 사용하셔서 불필요한 인스턴스 생성을 방지해주세요.

2021-05-25 12:32 UTC, ksundong commented on backend/src/main/java/com/example/airbnb/utils/SQL.kt
> +package com.example.airbnb.utils
파일명이 SQL인데, 이것보다 좋은 이름을 고민해보는게 좋다는 의견이 있습니다.
저라면 각각 사용되는 사용처마다 ~Query 정도로 만들 것 같은데 어떻게 생각하시나요?

2021-05-25 12:33 UTC, merged