[Team18 - Min, ZG (iOS)] 메인화면, 검색화면, 조건설정화면 구현
codesquad-members-2021/airbnb pull request #22
Opened 2021-05-24 08:02 UTC by jhpark-ZG

### 작업내용

- [ ] MVC 패턴으로 구현
- [ ] Alamofire로 네트워크 함수 작성
- [ ] 달력 FSCalendar 사용

### 고민한 내용

- conditionTableViewDataSource에서 같은 형식의 셀이 반복되지 않다 보니 if문을 사용해서 DataSource의 내부가 좀 지저분 해졌는데 마땅한 방법이 떠오르지 않아 고민한 상태로 남아있습니다. -> DataSource를 하나 더 선언하는 방법도 생각해 보았으나, 서로 다른 형식이 두개로 많지 않고 숙소 검색의 조건도 4가지로 고정이고 (향후 변동 가능성이 크지 않다고 생각하여) 선언하지 않고 if문으로 처리하였습니다.

- 조건설정화면에서 아래의 테이블뷰는 동일하고, 상단의 조건설정 화면만 바뀌는 형태여서 container View 를 사용하여 재활용을 하려다 어려움을 겪어 스크롤뷰에 스택뷰를 넣어 조건설정화면이 넘어가도록 구현했습니다.

### 부가사항

- class SearchResultData는 commit 실수로 들어간 파일이어서 리뷰에서 제외 부탁드립니다. 리뷰에 혼란을 드려 죄송합니다.

2021-05-24 11:53 UTC, GangWoon requested changes
전체적으로 하드 코딩이된 부분이 너무 많습니다. 
날 것 그대로 데이터보단 데이터에 의미를 부여해서 해당 프로젝트를 보는 사람 입장을 조금 더 배려해주셨으면 좋겠습니다.

두분이서 같이 작업을 하실 때, 컨밴션 룰을 정하셨으면 좋겠습니다. 코드의 일관성이 없어서 파일을 열람할 때 다른 프로젝트 같다는 느낌을 받았습니다.


`조건설정화면에서 아래의 테이블뷰는 동일하고, 상단의 조건설정 화면만 바뀌는 형태여서 container View 를 사용하여 재활용을 하려다 어려움을 겪어 스크롤뷰에 스택뷰를 넣어 조건설정화면이 넘어가도록 구현했습니다.`

위 부분은 사용자 입장에서 어색하지 않도록 잘 구현하신 거 같습니다.
해당 부분에서 state를 사용해서 처리를 하고 계신대, 조금 만 더 state를 사용해서 해당 뷰를 처리하면 좋을 거 같습니다. 하나의 Action 발생했을 때 state 중심으로 뷰를 제어하셨으면 좋겠습니다. 


`conditionTableViewDataSource에서 같은 형식의 셀이 반복되지 않다 보니 if문을 사용해서 DataSource의 내부가 좀 지저분 해졌는데 마땅한 방법이 떠오르지 않아 고민한 상태로 남아있습니다. -> DataSource를 하나 더 선언하는 방법도 생각해 보았으나, 서로 다른 형식이 두개로 많지 않고 숙소 검색의 조건도 4가지로 고정이고 (향후 변동 가능성이 크지 않다고 생각하여) 선언하지 않고 if문으로 처리하였습니다.`

하나의 객체에서 처리하기 보단 여러개의 객체에서 처리를 하는게 더 좋을 거 같습니다.
무엇보다도 0, 1, 2 란 의미를 알 수 없는 숫자로 분리를하셔서 읽는 사람은 이해를 하기 어려운 코드인 거 같습니다.

2021-05-24 11:53 UTC, GangWoon commented on iOS/airbnb/airbnb/Controller/ConditionViewController.swift
> +    @IBOutlet weak var BeforeButton: UIButton!
이름을 작성하실 때 카멜 케이스를 사용하시지 않는 이유가 있을까요?
추가적으로  IBOutlet사이에 일반 프로퍼티가 들어가 있는데 코드를 작성하실 때 룰이 존재했을까요?

2021-05-24 11:53 UTC, GangWoon commented on iOS/airbnb/airbnb/Controller/ConditionViewController.swift
> +    private var calendarView: CalendarView!
Type이 CalendarView!인 이유를 들을 수 있을까요?

2021-05-24 11:53 UTC, GangWoon commented on iOS/airbnb/airbnb/Controller/ConditionViewController.swift
> +    private let conditionData: ConditionData
어.. 해당 이름을 보고 무슨일을 하는 객체인지 파악하기 너무 어렵습니다.

2021-05-24 11:53 UTC, GangWoon commented on iOS/airbnb/airbnb/Controller/ConditionViewController.swift
> +    private var currentState: CurrentState
위 두가지에 차이점이 존재할까요?

2021-05-24 11:53 UTC, GangWoon commented on iOS/airbnb/airbnb/Controller/ConditionViewController.swift
> +        self.currentState = ConditionViewController.CurrentState.date
self.currentState= .date로 작성하셔도 동일하게 작동합니다.

2021-05-24 11:53 UTC, GangWoon commented on iOS/airbnb/airbnb/Controller/ConditionViewController.swift
> +        self.tableViewDataSource = ConditionViewTableViewDataSource.init(condition: self.conditionData)
`ConditionViewTableViewDataSource(condition:)`, `ConditionViewTableViewDataSource.init(condition:)`
두가지 형태로 초기화를 하셨는데 다르게 작성하신 이유가 있을까요?

2021-05-24 11:53 UTC, GangWoon commented on iOS/airbnb/airbnb/Controller/ConditionViewController.swift
> +        self.conditionViews.setContentOffset(CGPoint(x: conditionViews.contentSize.width/3 * CGFloat(currentState.value), y: 0), animated: true)
해당 코드는 프레임값을 하드 코딩하신 거와 동일합니다.
다른 방법은 없었을까요?

2021-05-24 11:53 UTC, GangWoon commented on iOS/airbnb/airbnb/Controller/ConditionViewController.swift
> +        if currentState == .people{
if currentState == .people { 사소한 코드 한 자 일수도 있지만 모두가 같이 보는 코드일 수 있기 때문에 조심하셔야합니다.

2021-05-24 11:53 UTC, GangWoon commented on iOS/airbnb/airbnb/Controller/ConditionViewController.swift
> +        self.adultCountLabel.text = String(peopleCount)
Int -> String 정도의 데이터 변환은 Model에서 해보시는 건 어떨까요?

2021-05-24 11:53 UTC, GangWoon commented on iOS/airbnb/airbnb/Controller/ConditionViewController.swift
> +        self.conditionData.update(maxCost: "₩150000")
해당 코드와 같이 의미 있는 코드는 따로 상수로 관리해보시는 것도 좋을 거 같습니다.

2021-05-24 11:53 UTC, GangWoon commented on iOS/airbnb/airbnb/Controller/ConditionViewController.swift
> +        self.conditionData.update(people: 1, plus: false)
plus라는 파라미터 이름이 많이 어색한 거 같습니다.

2021-05-24 11:53 UTC, GangWoon commented on iOS/airbnb/airbnb/Controller/ConditionViewController.swift
> +        case date = 0
타입 자체 많으론 표현하실 수 없었을까요?
Int라는 값이 정말 필요한지 의문입니다.

2021-05-24 11:53 UTC, GangWoon commented on iOS/airbnb/airbnb/Controller/ConditionViewController.swift
> +        case 0:
0, 1, 2 이렇게 해당 코드만 보고 어떤 일을 하는지 유추할 수 없는 상태입니다.
조금 더 의미있는 코드였으면 좋겠습니다.

2021-05-24 11:53 UTC, GangWoon commented on iOS/airbnb/airbnb/Controller/ConditionViewController.swift
> +        self.calendarView = CalendarView.init(frame: CGRect(origin: self.content.subviews[0].frame.origin, size: self.content.subviews[1].frame.size))
0번째, 1번째 어떤 걸 의미하지는 알 수 없는 뿐만아니라 빈 배열에 접근했을 때 앱크래쉬가 날 수 있는 위험한 부분인 거 같습니다.

2021-05-24 11:53 UTC, GangWoon commented on iOS/airbnb/airbnb/Controller/ConditionViewTableViewDataSource.swift
> +        case location = "위치"
enum 타입 rawValue를 사용한다면 한번쯤은 의심해볼 필요가 있을 거 같습니다.
정말 rawValue가 필요한것인가.
위에서 사용하셨던 custom.. 프로토콜을 채택하더라도 rawValue를 사용하는 게 아닌 다른 방법을 생각해보시는 게 더 좋을 거 같습니다.

2021-05-24 11:53 UTC, GangWoon commented on iOS/airbnb/airbnb/Controller/ConditionViewTableViewDataSource.swift
> +            let cell = tableView.dequeueReusableCell(withIdentifier: "locationPeoplecondition", for: indexPath) as! ConditionViewTableViewCell
강제 언래핑을 사용하신 이유를 알 수 있을까요?
식별자같은 경우엔 하드코딩으로 작성하기 보다 의미있는 상수로 보관하는게 유지보수하는 입장에서 더 좋을 거 같습니다.

2021-05-24 11:53 UTC, GangWoon commented on iOS/airbnb/airbnb/Controller/RecommendTripCollectionViewDataSource.swift
> +        return 5
5라는 숫자도 왜 5인지 유추하기엔 어려울 거 같습니다.

2021-05-24 11:53 UTC, GangWoon commented on iOS/airbnb/airbnb/Controller/SearchViewController.swift
> +        super.awakeFromNib()
viewDidLoad와 해당 메소드와 어떤 차이점을 갖고 있나요?
어떤 코드는 viewDidLoad에서 작업하셨는데 둘의 차이점에 대해서 듣고 싶습니다.

2021-05-24 11:53 UTC, GangWoon commented on iOS/airbnb/airbnb/Controller/SearchViewController.swift
> +        return places?.count ?? 0
타입 자체가 []?일 이유가 있을까요?

2021-05-24 11:53 UTC, GangWoon commented on iOS/airbnb/airbnb/Controller/SearchViewController.swift
> +        localSearch?.start { [weak self] (response, error) in
weak, unowned의 차이점을 알 수 있을까요?

2021-05-24 11:53 UTC, GangWoon commented on iOS/airbnb/airbnb/Controller/SearchViewController.swift
> +                print((String(describing: error)))
사용자 입장에선 아무런 정보도 알 수 없는 상황인데 꼭 있어야하는 코드인가요?

2021-05-24 11:53 UTC, GangWoon commented on iOS/airbnb/airbnb/Controller/SuggestionsTableViewController.swift
> +            // Each suggestion is a MKLocalSearchCompletion with a title, subtitle, and ranges describing what part of the title
불필요한 주석은 지워주시기 바랍니다.

2021-05-24 11:53 UTC, GangWoon commented on iOS/airbnb/airbnb/Controller/SuggestionsTableViewController.swift
> +        let attributes = [NSAttributedString.Key.backgroundColor: UIColor(named: "suggestionHighlight")! ]
하드코딩과 강제언래핑 조합은 다른 사람에게 혼돈이 될 수도 있습니다.

2021-05-24 11:53 UTC, GangWoon commented on iOS/airbnb/airbnb/Model/Data/ConditionPageData/ConditionData.swift
> +    init(){
필요한 생성자인가요?

2021-05-24 11:53 UTC, GangWoon commented on iOS/airbnb/airbnb/Model/Data/ConditionPageData/ConditionData.swift
> +final class ConditionData {
모델이 class일 필요가 있을까요?

2021-05-24 11:53 UTC, GangWoon commented on iOS/airbnb/airbnb/Model/Network/EndPoint.swift
> +struct MainAPIEndPoint: Requestable {
프로토콜과 구체타입의 차이점이 존재하지 않는데 프로토콜을 사용하신 이유를 들을 수 있을까요?

2021-05-24 11:53 UTC, GangWoon commented on iOS/airbnb/airbnb/Model/Network/FirstPageDTO.swift
> +struct FirstPageDTO: Decodable {
이름이 명확하긴 하지만 프로젝트를 유지보수하는 입장에선 조금 더 구체적이였으면 좋겠습니다.
이름 작성하시는 게 어려운 작업이지만 연습해보셨으면 좋겠습니다.

2021-05-24 11:53 UTC, GangWoon commented on iOS/airbnb/airbnb/View/CalendarView.swift
> +        let formatter: (Date) -> String = { (date) in
클로저로 작성하신 이유가 있을까요?

2021-05-25 01:37 UTC, jhpark-ZG commented on iOS/airbnb/airbnb/Controller/ConditionViewController.swift
> +    @IBOutlet weak var BeforeButton: UIButton!
아니에요. 룰은 따로 없었고.. 실수였습니다. 수정하였습니다!

2021-05-25 01:44 UTC, jhpark-ZG commented on iOS/airbnb/airbnb/Controller/ConditionViewController.swift
> +    private var calendarView: CalendarView!
초기화 하는 단계에서 calendarView 사이즈도 지정해주고 싶어서 그랬던 것 같습니다.

2021-05-25 01:56 UTC, jhpark-ZG commented on iOS/airbnb/airbnb/Controller/ConditionViewController.swift
> +    private let conditionData: ConditionData
findingAccommdationCondition로 수정하였습니다.

2021-05-25 02:20 UTC, youngminshim-de commented on iOS/airbnb/airbnb/Controller/ConditionViewController.swift
> +        self.conditionViews.setContentOffset(CGPoint(x: conditionViews.contentSize.width/3 * CGFloat(currentState.value), y: 0), animated: true)
프레임 값을 구하는 방식은 똑같은데 변수를 만들어 가독성이 향상되도록 수정하였는데,
이게 혹시 의도하신바와 일치하는지 궁금합니다..
아니면 다른 방법을 말씀하신건가요?

2021-05-25 02:25 UTC, jhpark-ZG commented on iOS/airbnb/airbnb/Controller/ConditionViewController.swift
> +        self.adultCountLabel.text = String(peopleCount)
모델에서 하도록 수정했는데.. 의도하신 바와 동일한지 잘 모르겠네요. ㅜ

2021-05-25 02:27 UTC, jhpark-ZG commented on iOS/airbnb/airbnb/Controller/ConditionViewController.swift
> +        self.conditionData.update(maxCost: "₩150000")
현재 아직 데이터 쪽이 구현되지 않아 UI만 보기위해 임시로 넣어 놓은 코드여서 데이터 쪽이 구현이 끝나면 수정할 예정입니다.

2021-05-25 02:41 UTC, jhpark-ZG commented on iOS/airbnb/airbnb/Controller/ConditionViewController.swift
> +        self.calendarView = CalendarView.init(frame: CGRect(origin: self.content.subviews[0].frame.origin, size: self.content.subviews[1].frame.size))
self.content.subviews[0] 이부분을 guard let 으로 처리하여 지역 변수로 contentFirst 선언하여 사용 했는데,
해당 변수에 addSubView하면 지역변수 이기 때문에 뷰가 추가되지 않을 줄 알았는 데, 추가 되었습니다.
해당 변수가 참조 타입이어서 혹시 메모리에 계속 남아 해제가 되지 않는 지 여쭤보고 싶습니다.

2021-05-25 02:47 UTC, jhpark-ZG commented on iOS/airbnb/airbnb/Controller/ConditionViewTableViewDataSource.swift
> +        case location = "위치"
말씀하신 내용중에 custom이 어느 부분을 말씀하시는 건지 잘 몰라 해당 문제를 수정하지 못했습니다.
custom은 CaseIterable을 말씀하시는 걸까요?
그리고 결과적으로 rawValue를 사용하지 않고 문제를 해결해보라는 말씀이신지 궁금합니다!

2021-05-25 02:50 UTC, Settpark commented on iOS/airbnb/airbnb/Controller/RecommendTripCollectionViewDataSource.swift
> +        return 5
말씀하신 숫자는 아직 데이터를 못 받아서 임시로 넣어 놓은 데이터라 데이터 들어오면 수정하도록 하겠습니다.

2021-05-25 03:08 UTC, youngminshim-de commented on iOS/airbnb/airbnb/Controller/SearchViewController.swift
> +        super.awakeFromNib()
사실 애플예제를 인용하다보니 중구난방으로 들어가게 된것 같습니다..
awakeFromNib 과 viewDidLoad 의 차이에 대해서는 잘 모르겠습니다
awakeFromNib이 ViewDidLoad 보다 먼저 호출이 되고, awakeFromNib 시점에는 프레임과 레이어에 관련된 값들을 처리한다고 하는데 제가 알고 있는게 맞는건가요?

2021-05-25 03:10 UTC, jhpark-ZG commented on iOS/airbnb/airbnb/Controller/SearchViewController.swift
> +        return places?.count ?? 0
mapkit의 결과 값이 nil 경우가 있을 수 있다고 생각하여서 이렇게 처리 하였는데 혹시 잘못된 처리방식이 었을까요??

2021-05-25 03:15 UTC, youngminshim-de commented on iOS/airbnb/airbnb/Controller/SearchViewController.swift
> +        localSearch?.start { [weak self] (response, error) in
코드상에 두개 다 존재하는 부분은 실수였던 것 같습니다.
unowned 보다 weak 이 보다 안전한 방법인 것 같아 unowned -> weak 으로 모두 수정하였습니다.

2021-05-25 03:22 UTC, GangWoon commented on iOS/airbnb/airbnb/Controller/ConditionViewController.swift
> +    @IBOutlet weak var BeforeButton: UIButton!
실수하실 수 있습니다. 꾸짖는게 아니니까 주눅들지 않으셔도 됩니다.

2021-05-25 03:22 UTC, GangWoon commented on iOS/airbnb/airbnb/Controller/ConditionViewController.swift
> +    private var calendarView: CalendarView!
IBOutlet과 달리 생성하는 시점을 조절할 수 있었는데 강제 언래핑일 필요가 있었을까요?

2021-05-25 03:23 UTC, GangWoon commented on iOS/airbnb/airbnb/Controller/ConditionViewController.swift
> +        self.conditionViews.setContentOffset(CGPoint(x: conditionViews.contentSize.width/3 * CGFloat(currentState.value), y: 0), animated: true)
스텍뷰로 구현하게 되면 프레임값으로 접근하지 않고 변경할 수 있을 거 같습니다.

2021-05-25 03:23 UTC, youngminshim-de commented on iOS/airbnb/airbnb/Model/Network/EndPoint.swift
> +struct MainAPIEndPoint: Requestable {
현재는 구체타입이 하나밖에 없지만, 추가적으로 url path들이 등장한다면 프로토콜을 채택하기 위하여 미리 만들어 두었습니다.

2021-05-25 03:24 UTC, GangWoon commented on iOS/airbnb/airbnb/Controller/ConditionViewController.swift
> +        self.adultCountLabel.text = String(peopleCount)
커밋을 추가하셔야, 체인지를 제가 확인할 수 있습니다.

2021-05-25 03:26 UTC, GangWoon commented on iOS/airbnb/airbnb/Controller/ConditionViewController.swift
> +        self.calendarView = CalendarView.init(frame: CGRect(origin: self.content.subviews[0].frame.origin, size: self.content.subviews[1].frame.size))
말씀하시는걸 정확하게 이해할 수 없어서 답변을 드릴 수 없을 거 같습니다. 
커밋이 추가되면 다시 확인해보도록 하겠습니다.

2021-05-25 03:26 UTC, jhpark-ZG commented on iOS/airbnb/airbnb/Model/Data/ConditionPageData/ConditionData.swift
> +    init(){
1. 그럼 속성 전부 옵셔널로 처리하고 생성자를 구현하지 말라는 의미이신가요?
2. 굳이 class가 아닌 struct로 작성하라는 의미이신가요?

생성자가 필요하냐는 질문은 처음 받아봐서 의미를 잘 파악을 못했습니다..

2021-05-25 03:29 UTC, GangWoon commented on iOS/airbnb/airbnb/Controller/ConditionViewTableViewDataSource.swift
> +        case location = "위치"
CustomStringConvertible을 채택한 enum을 말하는 거 였습니다.
아래와 같은 방법으로 표현할 수 있을 거 같습니다.
enum tableViewTitle: CustomStringConvertible {
    case location
    
    var description: String {
        switch self {
        case .location:
            return "위치"
        }
    }
}

추가적으로 tableViewTitle 타입자체 이름은 보통 TableViewTitle 이런 식으로 작성하는 거 같습니다.

2021-05-25 03:32 UTC, GangWoon commented on iOS/airbnb/airbnb/Controller/SearchViewController.swift
> +        super.awakeFromNib()
저도 자세하게 모릅니다.
다만 질문을 한 이유는 초기화 작업을 어떤 파일에선 viewDidLoad, 어떤 파일에선 awakeFromNib에서 하셨기때문에 질문을 한겁니다.
해당 코드를 읽는 사람 입장에선 "다른 이유가 있나"부터 생각을 하게 됩니다. 
`애플예제를 인용하다보니 중구난방으로 들어가게 된것` 는 다른 사람을 설득하기엔 부족한 정보같습니다.

2021-05-25 03:33 UTC, GangWoon commented on iOS/airbnb/airbnb/Controller/SearchViewController.swift
> +        return places?.count ?? 0
빈 배열 [], 과 nil ?? .zero 의 숫자는 동일하지 않나요?

2021-05-25 03:43 UTC, GangWoon commented on iOS/airbnb/airbnb/Model/Data/ConditionPageData/ConditionData.swift
> +    init(){
`그럼 속성 전부 옵셔널로 처리하고 생성자를 구현하지 말라는 의미이신가요?`
객체를 생성할 때 초기값이 없는 빈값을 생성하고 추후에 변경하는 접근은 위험한 방법이 될 수 있습니다.
해당 API를 사용 법을 모르는 사람이 값을 넣기전에 접근을 하게 되면 원하지 않는 결과를 초래할 수 있습니다.
생성할 때 의미있는 값을 넣어주는 건 어떨까요?

`굳이 class가 아닌 struct로 작성하라는 의미이신가요?`
어... 해당 질문에 대해선 많은 이야기거리가 있어서 제가 어떻게 설명드려야할지 어렵네요....
[link](https://medium.com/pinterest-engineering/immutable-models-and-data-consistency-in-our-ios-app-d10e248bfef8) 와 같이 왜 모델이 struct이면 좋은지에 대해서 공부를 해보시는 것도 좋을 거 같습니다.

2021-05-25 05:24 UTC, jhpark-ZG commented on iOS/airbnb/airbnb/Model/Data/ConditionPageData/ConditionData.swift
> +    init(){
`생성할 때 의미있는 값을 넣어주는 건 어떨까요?`
저희 프로젝트 특성상 사용자가 예약 조건을 설정할 때 구체적인 값이 들어가는 형태여서 처음에 ViewController에 클래스를 인스턴스하는 시점에는 빈 값이어서 이렇게 처리한 거 같습니다. 저희가 이 건에 대하여 해결 의도가 조금 헷갈리는 데,
1. init(location: String ...) 으로 매개변수를 넣고 생성 할때 빈값을 넣는 건지..
2. 처음부터 값이 비어있는 상태를 표시하고 싶다면 옵셔널로 모든 값을 처리하는 게 더 올바른 방향인지 잘 몰라서 이 부분 질문 드리고 싶습니다.

2021-05-25 10:38 UTC, GangWoon commented on iOS/airbnb/airbnb/Model/Data/ConditionPageData/ConditionData.swift
> +    init(){
아하 저는 보통 static let empty = Self()로 만들어두고 사용합니다.

2021-05-25 14:05 UTC, GangWoon commented on iOS/airbnb/airbnb/Controller/ConditionViewController.swift
> +        self.adultCountLabel.text = String(peopleCount)
네네 유사합니다 convert라는 메소드를 만드시는거보단 내부 데이터는 private로 숨기고 view에서 사용하는 데이터를

var someData: String {
     return "\(price) 원"
}
로 표현하면 덜 어색할 거 같습니다.

2021-05-25 14:12 UTC, GangWoon reviewed
해당 피알에서 고치실게 추가적으로 없다고 보면될까요?

2021-05-25 14:12 UTC, GangWoon commented on iOS/airbnb/airbnb/Model/Data/ConditionPageData/FindingAccommdationCondition.swift
> +        if self.people == nil {
이부분의 로직을 개선할 순 없을까요?

2021-05-26 08:50 UTC, merged