[Team-01 iOS] 메인 View부터 Price 설정 슬라이드 뷰까지의 흐름 UI 구현
codesquad-members-2021/airbnb pull request #40
Opened 2021-05-26 04:19 UTC by JUNGYUN-Daegu

안녕하세요 1팀의 iOS 개발을 담당하게된 JEJE입니다.🤓
그동안 전체적인 UI 흐름을 구현하려 했습니다.
그렇기 때문에 데이터를 활용한 비지니스 로직 구현 부분과 앱의 기본적인 구조는 아직 미흡한 프로젝트 같습니다.
잘 부탁드리겠습니다.

# Display

# 주요 구현 사항
- 후에 MVVM 패턴을 사용하기 위해 파일 시스템을 정리했습니다.
- Welcome Scene에서 검색 버튼을 누르면 숙소 Search Scene으로 넘어가도록 했습니다.
- 숙소 Search Scene에 Search Controller를 넣었습니다. (Search 기능과 데이터와의 연결은 진행하지 않았고 임시로 상수를 넣었습니다.)
- Search Scene에서 셀을 클릭하면 해당 셀의 행선지를 다음 뷰컨트롤러에 넘기도록 했습니다.
- 다음 뷰 컨트롤러인 SetUpViewController에서는 세부 설정을 하는 뷰가 차례대로 바뀌고 각 뷰에서 결정한 세부사항들을 컨테이너 뷰인 ReservationDetailView에 담도록 구현했습니다.
- Calendar 뷰는 외부 라이브러리를 사용했습니다.

# 질문 사항
- SearchView Scene에서는 콜렉션뷰에 Diffable Data Source를 사용했는데 Reservation Detail 컨테이너 뷰컨에서는 테이블 뷰에 dataSource delegate를 사용했습니다. 이게 앱 구조의 일관성을 해치는지, 아니면 이렇게도 사용이 가능한지 궁금합니다.

# 고민과 개선할 점(질문)
- 이때까지는 View Controller의 비지니스 로직을 따로 분리하기 위해 뷰 모델을 썼는데 SetUp 컨트롤러의 하위 뷰(CalendarControl, Price Control 뷰 등)가 하는 일이 많아지면서 뷰 모델로 분리할 필요성을 느끼게 됐습니다. 뷰와 모델을 분리하는 작업을 하긴 해야할텐데 이 경우 Controller의 뷰모델과 View의 뷰모델을 따로 구분해야 할까요?🧐

2021-05-26 13:56 UTC, GangWoon commented
안녕하세요 제제 이번 프로젝트 리뷰어 강운입니다.
제가 사전에 리펙토링이 중심적으로 할지, 기능 구현에 중점을 둘지 여쭤봤었는데요. 그 이유는 제제 의견을 맞춰드릴려고 질문했었습니다.
하지만 해당 코드를 보고 나서 느낀점은, 안티패턴으로 코드를 작성하고 계셔서, 이를 무시하고 진행하기엔 제 생각은 정말 코드 덩어리를 작성하실 거 같아서 다시 여쭤보려고 이렇게 글을 남깁니다. 이 부분이 혹시라도 기분이 나쁘시거나 불쾌하시다면 말해주시고, 그 즉시 기능 위주의 리뷰만 진행하도록 하겠습니다. 

`SearchView Scene에서는 콜렉션뷰에 Diffable Data Source를 사용했는데 Reservation Detail 컨테이너 뷰컨에서는 테이블 뷰에 dataSource delegate를 사용했습니다. 이게 앱 구조의 일관성을 해치는지, 아니면 이렇게도 사용이 가능한지 궁금합니다.`

정답은 없으나 제 생각은 일관성을 유지했으면 좋겠습니다.
반대로 왜 특정 부분은 Diifable을 사용하고 UITableViewDataSource를 사용하신건가요?

`이때까지는 View Controller의 비지니스 로직을 따로 분리하기 위해 뷰 모델을 썼는데 SetUp 컨트롤러의 하위 뷰(CalendarControl, Price Control 뷰 등)가 하는 일이 많아지면서 뷰 모델로 분리할 필요성을 느끼게 됐습니다. 뷰와 모델을 분리하는 작업을 하긴 해야할텐데 이 경우 Controller의 뷰모델과 View의 뷰모델을 따로 구분해야 할까요?🧐`

ViewModel을 나누는 건 원하시면 나누시면 됩니다. 그 결과로 객체마다 하는 일이 명확해질 수 있고, 반대로 불명확해 질 수 있습니다.
리펙토링은 순차적으로 진행됩니다. 처음부터 모든 걸 설계할 수 없기에 부분씩 고쳐나가는 겁니다.

코드 전체를 읽었을 때 현재 프로젝트는 어떤 패턴을 사용하고 계신지 질문하고 싶었습니다.
코드를 작성할 때 어떤 생각을 하면서 작성하시는 지 듣고 싶습니다.

2021-05-27 02:13 UTC, JUNGYUN-Daegu commented
리뷰 감사합니다~! 제 생각을 말씀드리자면

1.` 왜 특정 부분은 Diifable을 사용하고 UITableViewDataSource를 사용하신건가요?`
일반적인 데이터 소스의 단점은 콜렉션뷰나 테이블뷰의 데이터를 업데이트할 때 로컬에서 관리하고 있는 데이터와 차이가 나면 오류를 낸다는 것입니다. 그리고 제가 이해하고있는 Diffable Data Source의 장점은 이를 snapshot이 자동으로 관리해준다는 것이고 그렇기 때문에 데이터의 변화가 많은 SearchResultCollectionView에서는 Diffable Data Source를 사용했습니다. 반대로 ReservationDetailTableView는 처음에 지정한 셀의 수가 변하지 않는 비교적 정적인 구조라 사용하기 간단한 DataSource Delegate를 사용했습니다.
하지만 말씀해주신대로 일관성을 유지하는 것이 좋아보이네요 🤓. 반영하도록 하겠습니다~!

2. ```
ViewModel을 나누는 건 원하시면 나누시면 됩니다. 그 결과로 객체마다 하는 일이 명확해질 수 있고, 반대로 불명확해 질 수 있습니다.
리펙토링은 순차적으로 진행됩니다. 처음부터 모든 걸 설계할 수 없기에 부분씩 고쳐나가는 겁니다.
```
지금 CalendarControlView 같은 경우에 보여주는 코드 말고 로직을 처리하는 부분도 들어가고 있는데 이를 분리하는 것이 좀 더 명확해질 것 같네요. 말씀대로 순차적으로 리팩토리를 진행하도록 하겠습니다. 감사합니다~!

3. `일을 작은 단위로 나누는 작업도 정말 중요한 능력중 하나라고 생각합니다. ... 제제도 한 번 일을 작은 단위로 나누는 작업을 도전해보셨으면 좋겠습니다.`
피드백 감사합니다 😭. 노력하겠습니다

4. `코드 전체를 읽었을 때 현재 프로젝트는 어떤 패턴을 사용하고 계신지 질문하고 싶었습니다. 코드를 작성할 때 어떤 부분을 중점으로 생각하면서 작성하셨는지 듣고 싶습니다.`
전체적으로 MVVM 패턴에 클린 아키텍처를 적용해보고 싶었습니다. 아직 Data와 Domain 파일이 휑하고 Presentation 파일만 꽉찬 이유는 전체적인 UI 흐름을 먼저 구성해보고 싶었기 때문입니다. 결론적으로 작업 단위가 깔끔하게 나눠지지 않게되는 단점이 됐네요.

2021-05-27 02:55 UTC, GangWoon requested changes
UI중심으로 작성하셨기에 데이터의 흐름이 파악하시지 못하고 계십니다.
우선 View와 Model을 분리하시고 데이터의 흐름을 파악하시는게 좋아보입니다.

하나의 메소드에서 엄청 여러가지의 이벤트가 발생하고 있습니다.
이를 제제가 생각했을 때 의미가 있는 단위로 분리하셨으면 좋겠습니다.

상위 객체로 접근할 때 "어떻게든 타입 캐스팅해서 접근"보다는 객체를 주입받거나 추상화를 시켜서 접근하는 방식이 좋을 거 같습니다.

예를 들어서 ReservationDetailViewControllerProtocol를 작성하신 거 처럼 구체타입은 숨키면서 외부 인터페이스를 제공하는 형식을 말하는겁니다. 처음부터 엄청난 추상화를 하기보단 필요한 데이터가 있다면 갖고 와서 사용하는 방식이 됐으면 좋겠습니다.

혹시라도 구현하시다가 어려움이 있다면 편하게 질문하셨으면 좋겠습니다.

2021-05-27 02:55 UTC, GangWoon commented on iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/Controllers/ReservationDetailViewController.swift
> +        print("reservatinDetail did load")
해당 로그 같은 경우에는 디버그하실 때만 보였으면 좋겠습니다.

2021-05-27 02:55 UTC, GangWoon commented on iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/Controllers/ReservationDetailViewController.swift
> +            (parent as? SetUpViewController)?.calendarControlView?.clearCalendarView()
위와 같은 접근은 피하면 정말 좋을 습관 같습니다.
왜냐하면 코드가 정말 종속적이게 됩니다. 이를 피하기 위해서 추상화를 해서 사용하시면 됩니다.

2021-05-27 02:55 UTC, GangWoon commented on iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/Controllers/ReservationDetailViewController.swift
> +
동일합니다.

2021-05-27 02:55 UTC, GangWoon commented on iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/Controllers/ReservationDetailViewController.swift
> +        let cell = reservationDetailTableView.cellForRow(at: indexPath) as? ReservationDetailTableViewCell
해당 부분을 보고서 느낀점은 정적인 요소여서 UITableViewDataSource를 사용하셨다고 하셨는데,
반대로 정적인 부분에 UITableView를 사용하신 이유가 있을까요?
추가적으로 UILabel 즉 레퍼런스 타입을 리턴하는 방식은 어디서나 원할 때 해당 객체를 변경할 수 있는 반면에 비동기적인 작업을 하시게 되면 원치않는 결과와 디버깅을 하실 때 혼란을 경험하실 겁니다.

2021-05-27 02:55 UTC, GangWoon commented on iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/Controllers/SearchViewController.swift
> +    }
구현하지 않는 코드들은 삭제하셨으면 좋겠습니다.
읽는 사람에겐 해당 코드가 왜있는지 의문이 생깁니다.

2021-05-27 02:55 UTC, GangWoon commented on iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/Controllers/SearchViewController.swift
> +        view.addSubview(searchResultCollectionView)
UICollectionView가 프레임 값으로 뷰를 배치하시는 작업입니다.
해당 코드를 이쁘게 포장하셨지만 사실상 
iPhone 6은  ** iPhone 12 Pro는 ** 으로 하드코딩한 거 와 같다는 느낌을 줍니다.

또한 UIApplication.shared.windows[0] 와 같은 뷰 계층을 뛰어넘어 글로벌 객체에 접근하시는 방법은 iOS 버전, 기기별로 검색해도알 수 없는 버그들이 존재합니다. 이를 피하시기 위해서 다른 방법을 생각해보셨으면 좋겠습니다.

2021-05-27 02:55 UTC, GangWoon commented on iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/Controllers/SetUpViewController.swift
> +    public var priceSlideControlView: PriceSlideControlView! = nil
해당 API를 어떻게 사용하는지 모르는 사람이 접근했을 때 앱크래쉬가 날 수 있는 안좋은 습관 중 하나입니다.
최대한 강제 언래핑은 피하셨으면 좋겠습니다.

2021-05-27 02:55 UTC, GangWoon commented on iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/View/CalendarView/CalendarControlView.swift
> +            }
해당 로직은 의미가 있는 로직을 여러개로 분리해서 작성하셨으면 좋겠습니다.
다른 사람이 해당 로직을 보고 이건 뭐지.... 라는 생각부터 들 거 같습니다.
의미가 있는 코드량만큼 분리해서 메소드로 분리한다면 좋을 거 같습니다.

2021-05-27 03:35 UTC, JUNGYUN-Daegu commented on iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/Controllers/ReservationDetailViewController.swift
> +        let cell = reservationDetailTableView.cellForRow(at: indexPath) as? ReservationDetailTableViewCell
오! 감사합니다. 애초에 UI 테이블 뷰로 구현할 필요가 없었던 것 같습니다.
추가적으로 말씀해주신 레퍼런스 타입을 리턴하는 방식도 다음부터는 장단점을 파악해서 구현하도록 해야겠네요👍

2021-05-27 06:34 UTC, JUNGYUN-Daegu commented on iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/Controllers/SearchViewController.swift
> +        view.addSubview(searchResultCollectionView)
좋은 피드백 감사합니다.🤓 `UIApplication.shared.windows[0] 와 같은 뷰 계층을 뛰어넘어 글로벌 객체에 접근하시는 방법은 iOS 버전, 기기별로 검색해도알 수 없는 버그들이 존재`한다는 사실은 정말 알기 쉽지 않은데 이번 기회에 많이 배우는 것 같습니다.

2021-05-27 06:37 UTC, JUNGYUN-Daegu commented on iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/Controllers/SearchViewController.swift
> +        view.addSubview(searchResultCollectionView)
더불어 CollectionView를 이니셜라이징하는 방법도 개선했습니다~!

2021-05-27 06:59 UTC, JUNGYUN-Daegu commented on iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/View/CalendarView/CalendarControlView.swift
> +            }
참고해서 로직을 분리해봤습니다~! 가독성이 매우 안좋은 코드를 쓰고 있었네요... 매우 반성하고 있습니다 🤯

2021-05-27 08:42 UTC, GangWoon approved these changes
목표중 하나였던 MVVM 패턴으로 넘어가기 전에 Model과 View를 나누는 작업을 하셨으면 좋겠습니다.
앞으로의 코드는 수정하신 코드처럼 의미가 있게 분류하시면 좋을 거 같습니다.
하시는 작업도 작게 나누시는 연습도 하셨으면 좋겠고요.
PR을 올리는 순간 더 이상 코드를 고칠 수 없다고 생각하시지 않으셔도 됩니다.
어떤 기능까지 다 만들어야지 보단 단위를 작게작게 나눠서 해당 유닛끼리의 관계가 어렵거나 그러실 때도 우선 PR을 올리고 같이 생각해보는 방법도 좋을 거 같습니다.

다음 PR에서 뵙겠습니다.

2021-05-27 08:42 UTC, merged

2021-05-27 08:55 UTC, JUNGYUN-Daegu commented
좋은 리뷰 감사합니다~! 다음 PR 뵙겠습니다~🤓