[team-4 롤로] 커스텀 캘린더(UI + 모델) + d
codesquad-members-2021/airbnb pull request #63
Opened 2021-05-31 07:29 UTC by eeeesong

안녕하세요 강운! 
지난주 구현 내용에 대한 PR 요청드립니다 :)

-----

### 현재 화면

### 구현 내용

#### 캘린더 

- 코드로 캘린더 선택 화면 UI 구성
- 캘린더 생성 및 날짜 선택 모델 생성
   - DateSelectionManager: 선택 날짜 관리, 달력 드래깅에 따른 달력 생성 관리
   - CalendarManager: 달력 선택 업데이트 관리, 달력 생성
   - Month: Day 상태 변경, 특정 날짜 반환
   - CalendarCoordinate: 캘린더 셀 선택 indexPath를 month, day 좌표 정보로 저장
- 숙박 조건 테이블 뷰에 유저 선택 상황 표시

### 고민 사항

2021-05-31 13:42 UTC, GangWoon requested changes

2021-05-31 13:42 UTC, GangWoon commented on IOS/airbnb/airbnb/AppCycle/SceneDelegate.swift
> +    private let homeCreator = HomeDIContainer()
이름 작명 아주 마음에 듭니다 :)

2021-05-31 13:42 UTC, GangWoon commented on IOS/airbnb/airbnb/AppCycle/SceneDelegate.swift
> +
해당 부분에서 디펜던시를 넘겨주면 좋을 거 같은데 생성만 하시고 사용하시진 않으셨네요?

2021-05-31 13:42 UTC, GangWoon commented on IOS/airbnb/airbnb/Main/ViewController/HomeViewController.swift
> +        homeViewController.viewModel = viewModel
UIKit 기반으로 프로그래밍 하실 때 VIew 즉 UIViewController는 생성할 때 가볍게(디펜던시가 적어야)생산할 수 있어야 좋습니다.
해당 이유는 따로 뷰만 생성해서 잘 만들어지고 있는지 테스트할 때 디펜던시가 무겁게 되면 역으로 해당 디펜던시를 생성하는 게 큰 작업이 되거든요. 그래서 필수로 넣어주는 것보단 생성을하고 추후에 넣어주는 방식으로 타입이 ?이면 좋겠죠? 이런 식으로 진행하시는게 더 좋습니다.

그러니까 모든 게 완성된 viewController를 리턴하는게 아닌 덜 완성된 viewController을 리턴하고 사용하는 곳에서 넣어주는 형태를 말합니다.

2021-05-31 13:42 UTC, GangWoon commented on IOS/airbnb/airbnb/Main/ViewModel/HomeViewModel.swift
> +            dataHandler?(cacheUrl)
cacheUrl.map { self.dataHandler?($0) }으로 간단한 가드문을 제거할 수도 있습니다.

2021-05-31 13:42 UTC, GangWoon commented on iOS/airbnb/airbnb/AccommodationConditions/CalendarSelect/Model/DateSelectionManager.swift
> +        case 3:
enum을 사용해서 의미 있는 데이터를 사용해보시는 건 어떨까요??
enum  Selection: Int {
case one = 1
}
switch Selection(rawValue: selectedCoords.count) {
case one:
..

이런 식으로요

2021-05-31 13:42 UTC, GangWoon commented on iOS/airbnb/airbnb/AccommodationConditions/CalendarSelect/Model/DateSelectionManager.swift
> +            fillBetween(selectedCoords[0], selectedCoords[1], to: .none)
엄청 크리티컬한 부분은 아니지만 해당 컴포넌트들에게 의미를 부여하면 읽는 사람이 이해하는 도움을 줄 수 있습니다.
let someItem = selectedCoords[0]
...

2021-05-31 13:42 UTC, GangWoon commented on iOS/airbnb/airbnb/AccommodationConditions/CalendarSelect/Model/Month.swift
> +final class Month {
클래스인 이유를 들을 수 있을까요?

2021-05-31 13:42 UTC, GangWoon commented on iOS/airbnb/airbnb/AccommodationConditions/CalendarSelect/View/AccommodationConditionTableViewCell.swift
> +    lazy var conditionTitle: UILabel = {
뷰같은 경우에 인터페이스를 외부로 노출시키는 것보다 
var title: String? { willSet { conditionTitle.title = newValue } } 이런 식으로 하는 게 더 좋다고 생각합니다.

2021-05-31 13:42 UTC, GangWoon commented on iOS/airbnb/airbnb/AccommodationConditions/CalendarSelect/View/CalendarCollectionViewCell.swift
> +    func futureMode() {
아래와 같이 상태를 관리하는 할 때 enum으로 관리하시고 프로퍼티 옵저버를 사용해서 조금 더 이쁘게 꾸미실 수 도 있습니다.

2021-05-31 13:42 UTC, GangWoon commented on iOS/airbnb/airbnb/AccommodationConditions/CalendarSelect/View/CalendarCollectionViewCell.swift
> +        if isEdge {
셀 자체 상태로는 불가능 하셨나요?

2021-05-31 13:42 UTC, GangWoon commented on iOS/airbnb/airbnb/AccommodationConditions/CalendarSelect/ViewController/CalendarCollectionViewDataSource.swift
> +        return cell
개인적인 생각입니다.
작성하신 코드도 충분히 잘하셨는데 셀을 꾸미는 건 내부로 숨키고 상태를 변경해서 해당 셀의 모습을 바꾸는 방식이 전 더좋다고 생각합니다.

2021-05-31 13:42 UTC, GangWoon commented on iOS/airbnb/airbnb/AccommodationConditions/CalendarSelect/ViewController/CalendarCollectionViewDataSource.swift
> +        switch kind {
해당 부분도 String을 필터하는 것 보단 의미가 있는 것으로 둔갑시켜서 사용하시는 게 더 이쁠 거 같습니다.
guard case .some = SomeEnum(rawValue: "") else { return }
이런식으로요.

2021-05-31 13:42 UTC, GangWoon commented on iOS/airbnb/airbnb/AccommodationConditions/CalendarSelect/ViewController/CalendarViewController.swift
> +        return toolBar
클로저 내부에서 모든 걸 설정하는 것보다 의미가 있는 것들끼리 나눠서 해당 부분을 합치는 건 라이프 사이클중에서 처리를 하는게 어떨까요?
추가적으로 외부로 노출 시킬필요가 없는 뷰들은 사용하고 버린 부분은 정말 잘하신 듯합니다 👍

2021-05-31 13:42 UTC, GangWoon commented on iOS/airbnb/airbnb/AccommodationConditions/CalendarSelect/ViewController/CalendarViewController.swift
> +    private var accommodationConditionTableViewDataSource: AccommodationConditionTableViewDataSource?
저는 아래와 같은 순서대로 정렬하긴 합니다. 보통 중간에 프로퍼티가 들어가면 코드를 읽을 때 햇갈리더라구요 ㅋㅋㅋ
고치시라고 강요하는 부분은 아니지만 이질감을 느껴서 말씀드립니다.
views
properties
init
lifecycle
method
objc

2021-05-31 13:42 UTC, GangWoon commented on iOS/airbnb/airbnb/AccommodationConditions/CalendarSelect/ViewController/CalendarViewController.swift
> +        self.accommodationConditionTableViewDataSource = AccommodationConditionTableViewDataSource()
viewController에서 생성하는 대 필요한 폰트 컬러 스트링 값을 제외한 모든 Environment 즉 디펜던시는 생성할 때 넣어주는게 좋습니다.
viewDidLoad()에서 생성해서 작업할 시 로직을 테스트할 때 분리하시기 어려우실 수도 있습니다.

2021-05-31 13:42 UTC, GangWoon commented on iOS/airbnb/airbnb/AccommodationConditions/CalendarSelect/ViewController/CalendarViewController.swift
> +            if conditions[1] != "" {
조금더 의미가 있는 분기문이 됐으면 좋겠습니다.

2021-05-31 13:42 UTC, GangWoon commented on iOS/airbnb/airbnb/AccommodationConditions/CalendarSelect/ViewModel/CalendarViewModel.swift
> +    static let weekdays = ["일", "월", "화", "수", "목", "금", "토"]
이런 로우한 데이터를 이쁘게 포장하면 좋을 거 같습니다.
enum Day: customString... {
case monday

2021-05-31 13:49 UTC, GangWoon commented
```
ViewModel 중복 개선
ViewModel의 중복 코드를 개선하면서 protocol에 associatedtype을 쓰게 되었는데, 그러면서 구체 타입(class)를 생성하게 됐습니다.
프로토콜 -> 제네릭한 구체타입(Any---ViewModel) -> 구체타입 순으로 구체화를 하게되었는데, 이렇게 구현을 해도 괜찮은 것인지 약간 확신이 서지 않습니다😅 중복은 줄일 수 있었지만, 협업 등의 차원에서 위험성은 없는지 고민이 있었습니다.
```

해당 부분은 제네릭한 구체타입을 제거할 수 있는 방법이 있습니다. 중간 객체를 제거하는 방법을 시도해보셔도 좋을 거 같습니다.


```
ViewController에 필요한 객체들을 외부에서 주입해주는 방식을 시도해보았습니다. 가장 처음 나타나는 HomeViewController는 SceneDelegate를 통해서 주입을 해주었고, 앱 시작 단에서 주입을 해주는 방식이 괜찮다고 느껴져서 다른 ViewController들에도 적용을 해보려고 시도를 해보았습니다.
그러나 결과적으로는 아직 다소 어렵다고 느껴져서 직전 ViewController에서 주입해주는 것까지만 구현을 하고 PR을 보내게 되었습니다.
추후 천천히 더 공부를 해보고 수정해보면 좋을 것 같습니다...🙂
```

좋은 시도를 하셨던 거 같습니다. 처음부터 해당 개념을 이해하고 적응하기에 짧은 시간이였고 지금 당장 해달라고 요청드린 것도 아니였습니다.
나중에 생각이 나면 다시 도전해보시고 "왜 인젝션을 헤야하는지" 에 대해서 다른 사람에게 설명하실 수 있게 되면 좋을 거 같습니다.

view를 코드로 작성하게 되면 커스텀 할 수 있는 영역이 넓어지게 됩니다.
추가적으로 로우한 데이터를 사용하는 것보다 의미를 만들어주면서 이쁘게 꾸밀 수 있는게 개발자의 기술인 거 같구요.
정말 잘하셨지만 한번쯤은 바꿔보는 게 어떤지 조심스럽게 여쭤보고 싶습니다. 
위 체인지를 원치 않아면 말씀해주시고 프로토콜과 관련된 부분만 처리하시고 넘어가셔도 충분할 거 같습니다. 

데이터를 핸들링할 때 따로 객체를 만드셔서 처리하는 부분이 너무 마음에 들었습니다. 
추가적으로 이번 천줄은 로직을 포함한 천줄이여서 집중하기 조금 어려웠습니다 ㅋㅋ..
코맨트에서 놓친 부분에서 궁금한 점이 있거나 뭔가 애매한 부분이 있다면 언제든지 편안하게 질문하셨으면 좋겠습니다.

2021-06-01 01:10 UTC, eeeesong commented
@GangWoon 빠르게 피드백 남겨주셔서 정말 감사드립니다 :) 
상세 코멘트들도 꼼꼼하게 읽어보고 반영 및 질문드리도록 하겠습니다!

인젝션 관련해서는 어제 PR을 보내고 나서 다음 화면 흐름을 구성하려고 보니
지금 구조에서 다음 흐름으로 전 화면의 데이터를 넘겨주려면
당장 Container들과 Dependency 주입 구현이 필요하겠다는 생각이 들었습니다😅
그래서 해당 부분은 다음 흐름을 짜면서 바로 수정 반영을 해보는 방향이 될 것 같습니다!


```
추가적으로 로우한 데이터를 사용하는 것보다 의미를 만들어주면서 이쁘게 꾸밀 수 있는게 개발자의 기술인 거 같구요.
```

-> 이 부분은 말씀하신대로 의미를 만드는 것이 좋은 것 같아서 수정을 해보도록 하겠습니다 :) 

```
프로토콜과 관련된 부분만 처리하시고 넘어가셔도 충분할 거 같습니다.
```

-> 혹시 이 부분은 ViewModel 관련한 부분을 말씀하시는 걸까용??

그리고 struct와 class에 관해서는 해당 타입의 프로퍼티를 변경하게 되는 메소드가 들어갈 경우 class를 사용하고,
초기화 이후 내부 프로퍼티가 변경되지 않을 경우 struct를 사용했습니다. 
그래서 한번 만들어진 이후 바뀌지 않는 Day나, 매번 새로 만들어서 사용하는 CalendarCoordinate 같은 경우엔 struct를 쓰게 되었습니다!

2021-06-01 02:42 UTC, GangWoon approved these changes

2021-06-01 02:42 UTC, merged