[team-15] oauth 구현
codesquad-members-2021/airbnb pull request #66
Opened 2021-06-01 07:18 UTC by ChoiGiSung

안녕하세요. 백엔드 반의 coco입니다.
리뷰를 원하는 특정 코드만 코멘트 달아 놓을 테니 중점적으로 봐주셨으면 감사하겠습니다.

* GetPropetyUtil  은 applicationContext에서 property를 얻어오는 유틸입니다.
* GitHubDeviceType enum은 ios와 fe의 gitOauthApp을 분리 시키기 위한 enum입니다.

부족한 코드지만 봐주셔서 감사합니다.

2021-06-01 07:42 UTC, ChoiGiSung reviewed
리뷰를 원하는 로직들 입니다. 나머지는 crud 수준이라 밑의 코드에 대한 리뷰어님의 생각을 알고 싶습니다.

2021-06-01 07:42 UTC, ChoiGiSung commented on backend/src/main/java/com/codesquad/coco/oauth/gitoauth/GitHubDeviceType.java
> +    }
enum 초기화 부분입니다. util을 통해 secretKey.properties에서 값을 꺼내 초기화 시키는 로직입니다.
위의 코드로 인해 enum은 비밀 키를 가질 수 있게 되었습니다.

2021-06-01 07:42 UTC, ChoiGiSung commented on backend/src/main/java/com/codesquad/coco/oauth/gitoauth/GitOauth.java
> +        this.redirectUri = gitHubDeviceType.getRedirectUri();
converter로 받은 enum에서 비밀 키를 꺼내서 사용합니다.
enum은 생성될 때 property를 가지고 와서 초기화 합니다

2021-06-01 07:42 UTC, ChoiGiSung commented on backend/src/main/java/com/codesquad/coco/room/model/Room.java
> +    }
예약 검사 로직입니다. 
날짜와 인원 수 , 총 금액을 검사하는 로직 입니다.
 domain에서 모든 검사를 하는 메소드를 만들어 이것만 노출 시키는 것이 좋은지.
아님 service에서 각 검사 별로 따로 노출 시키는 게 좋을 지 고민이었습니다.

현재는 모든 검사를 하는 하나의 메소드 노출 시켜 사용하고 있습니다.

2021-06-02 13:57 UTC, ksundong commented
제가 원래 오늘 리뷰하려고 했는데 사정이 있어서 내일 하겠습니다! 죄송합니다!

2021-06-03 16:04 UTC, ksundong requested changes
안녕하세요! Coco! 리뷰어 Dion입니다.
리뷰 할 양이 많아서 조금 걸렸습니다. 양해부탁드려요 ㅠㅠ

프로젝트를 진행하느라 정말 고생많으셨습니다.
특히 단위테스트를 시도해보신 점 정말 좋은 것 같아요. 그리고 잘 하셨다고 생각됩니다.

사실 리뷰를 원하는 로직들이 무엇을 리뷰를 원하는건지 잘 이해가가지 않았습니다.
어떤 부분에 대한 리뷰를 요청하신건지 특히 Enum부분은 이해가 가지 않아서 별다른 리뷰역시 남기지 않았습니다.

고생하셨습니다~ 제가 생각하는 개선방향을 코멘트에 남겨두었으니 확인해주세요.
확인 하신 후에 생각하는 개선 포인트를 작성해주시면, 확인하고 머지해드리겠습니다~

2021-06-03 16:04 UTC, ksundong commented on backend/build.gradle
> +    implementation files('build/libs/gitOauthV1.jar')
직접 만들어 주신건가요?

2021-06-03 16:04 UTC, ksundong commented on backend/docker/db/conf/custom.cnf
> +collation-server = utf8_unicode_ci
해당 charset을 사용하는건 현 시점에선 추천드리지 않습니다.

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/city/CitiesDTO.java
> +    private List<CityDTO> cities;
Collection은 널 방지를 해주는 것을 추천합니다.

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/city/CityController.java
> +    private CityService cityService;
```suggestion
    private final CityService cityService;
```

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/city/CityController.java
> +    @GetMapping("/cities")
이정도는 미래지향적인 설계로 RequestMapping을 추출해보는것도 나쁘지않다고 생각합니다.

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/city/CityDAO.java
> +@Component
Repository 애노테이션을 보통 많이 사용하는데요
둘의 차이를 학습해보세요.

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/city/CityDAO.java
> +        return template.query(FIND_ALL,new CityMapper());
```suggestion
        return template.query(FIND_ALL, new CityMapper());
```

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/city/CityDTO.java
> +package com.codesquad.coco.city;
패키징을 좀 더 잘 해보시면 좋을 것 같아요.
모든 것이 한 패키지에 있는건 별로 추천드리고 싶지 않은 형태네요~

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/city/CityService.java
> +                .map(DTOConverter::cityToCityDTO)
컨버터가 꼭 필요할까요?

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/city/CityService.java
> +                .map(DTOConverter::cityToCityDTO)
생성자 내지는, 정적 팩토리 메서드를 활용해보면 어떨까 싶네요~

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/global/ApplicationContextServe.java
> +public class ApplicationContextServe implements ApplicationContextAware {
왜 사용해주셨는지 궁금해지는군요.

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/global/auth/UserIdHandlerMethodResolver.java
> +        Object infoFromJWT = JWTUtils.getInfoFromJWT(jwt, serverKey.getJwtServerKey(), WANT_INFO);
JWtUtils에 id를 얻어오는 함수를 만들어주는 것도 괜찮았겠네요.

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/global/exception/CustomExceptionHandler.java
> +
여기 빈 줄은 왜 띄워주신걸까요?

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/global/exception/CustomExceptionHandler.java
> +    @ExceptionHandler(OverTimeException.class)
주석과 예외명이 매칭이 되지는 않는 것 같네요.

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/global/exception/CustomExceptionHandler.java
> +    @ResponseStatus(HttpStatus.FORBIDDEN)
403을 기본으로 주는게 맞는지 고민해보세요.

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/global/exception/CustomExceptionHandler.java
> +    @ResponseStatus(HttpStatus.FORBIDDEN)
403에러는 언제 반환되어야 할까요?

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/global/exception/ErrorCode.java
> +    TOTAL_PRICE_NON_MATCH(422, "클라이언트의 총액과 일치하지 않음 : "),
상세한 에러코드의 사용 좋네요.

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/global/exception/ErrorCode.java
> +    INVALID_INPUT(404, "잘못된 입력"),
잘못된 입력이 404일까요?

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/global/exception/ErrorCode.java
> +    UNAUTHORIZED_JWT(404, "jwt를 확인 하세요"),
여기도 404가 맞을까요?

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/global/exception/ErrorCode.java
> +        this.message += valueOf;
파라미터명을 좀 더 제대로 바꿔주시는게 좋을 것 같아요.

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/global/exception/business/NonReservationException.java
> +    public NonReservationException() {
NonReservation은 뭔가 비문에 가까운 느낌이네요.
AlreadyReserved정도가 낫지않을까요?

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/global/exception/business/notfound/NotFoundRoomException.java
> +        super(ErrorCode.USER_NOT_FOUND);
에러코드가 뭔가 잘못된 것 같은데요?

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/global/exception/business/notfound/NotFoundUser.java
> +public class NotFoundUser extends NotFoundException {
네이밍이 달라졌네요.

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/image/Image.java
> +    private String type;
Enum을 써보는건 어땠을까요?

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/oauth/ServerKey.java
> +        logger.debug(jwtServerKey);
이래도 괜찮을까? 하는 생각이 들긴하네요.
객체 안에서 한 번도 로깅해볼 생각을 안해봤어서...
일단 써보시죠!

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/oauth/gitoauth/GitOauth.java
> +public class GitOauth extends Oauth {
상태때문에 추상클래스를 써주신걸까요?

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/oauth/gitoauth/GitOauth.java
> +public class GitOauth extends Oauth {
뭔가 메서드가 구현되어있는 것 같긴한데, 인터페이스를 사용하는게 더 낫지 않았을까? 하는 생각이 듭니다.

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/oauth/gitoauth/GitOauth.java
> +    public void changeType(GitHubDeviceType gitHubDeviceType) {
왜 바꿀 수 있나요?

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/room/RoomController.java
> +    @GetMapping("/search/prices")
search라는 동사를 넣어주신 이유가 있나요?

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/room/RoomDAO.java
> +    private ImageDAO imageDAO;
DAO를 가져다 쓰는 이유가 뭔가요?

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/room/RoomDAO.java
> +            fillRoomWithReservation(room);
왜 N + 1을 만들어주셨는지 궁금하네요.

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/room/model/AdditionalCost.java
> +public class AdditionalCost {
이 클래스는 하려고 했던 것이 맘에 드네요.

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/room/model/Guest.java
> +        baby = baby != null ? baby : 0;
그냥 primitive type을 받는건 어떤가요..?

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/room/model/Location.java
> +    private City city;
City가 같이 있는 편이 나았나요?

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/room/model/Location.java
> +    private double longitude;
이 값들은 값 객체로 표현되는게 좋지 않았을까요?

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/room/model/Money.java
> +public class Money {
좋은 시도네요.

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/room/model/Money.java
> +    private static final int MAX_PRICE = 999_999_999;
```suggestion
    public static final Money MIN_PRICE = new Money(0);
    public static final Money MAX_PRICE = new Money(999_999_999);
```

이런건 어때요?

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/room/model/Money.java
> +    }
뭔가 이상하지 않나요? ㅎㅎ

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/room/model/Review.java
> +    private double review;
왜 double 형인지, Entity로 관리되어야 하는지 궁금하네요.

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/room/model/Room.java
> +    }
`int fewNights = LocalDateUtil.getAccommodationDay(reservationDTO.getCheckIn(), reservationDTO.getCheckOut());`
일단 이렇게 계산하는 부분 별로 맘에 들지 않구요.
getter 사용하지않고 계산해보세요.

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/room/model/Room.java
> +    }
예약 검사를 하는 로직이고, 말씀하신게 모두 필요하다면 당연히 이쪽에서 해주는게 맞습니다.
다만, 이런 식의 메서드 추출은 좋은 형태가 아니라고 보여지네요.

1. 날짜 검사는 Reservation List를 이용하면 되지 않을까요? 일급 컬렉션을 사용하면 좋을 것 같네요.
2. 인원 수에 대한 검사는 인원수를 담당하는 클래스가 수행하면 되겠죠.
3. 총 금액 역시 총 금액을 담당하는 클래스가 수행하면 되겠죠.

결국 객체지향적으로 설계한다면, 내가 처리할 수 없는 책임은 다른 메서드를 추출해서 해결하는 것이 아니라, 다른 객체에게 책임을 위임하는 식으로 설계하는 것이 맞습니다.

2021-06-03 16:04 UTC, ksundong commented on backend/src/test/java/com/codesquad/coco/ReservationTest.java
> +public class ReservationTest {
시도 자체로 정말 높은 점수 드리고 싶네요 ㅎㅎ

2021-06-03 16:04 UTC, ksundong commented on backend/src/test/java/com/codesquad/coco/ReservationTest.java
> +        Room room = getRoom();
Room에 대한 가격을 인자로 넘겨준다면 좀 더 추측가능한 테스트코드가 되지않을까요?

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/room/model/dto/SearchPriceDTO.java
> +    protected String cityName;
왜 Protected일까요?

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/room/model/dto/SearchPriceDTO.java
> +    @ConstructorProperties({"check-in", "check-out", "city-name"})
저는 처음 보는 애노테이션이군요 ㅎㅎ

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/room/model/dto/SearchRoomDTO.java
> +public class SearchRoomDTO extends SearchPriceDTO {
이래서군요..
추상클래스로 바꿔주세요 ㅎㅎ

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/room/model/dto/SearchRoomDTO.java
> +    @ConstructorProperties({"check-in", "check-out", "city-name", "adult", "child", "baby", "price-min", "price-max"})
딱히 필요없어보이는데 작성해주신 이유가 뭘까요?

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/user/UserService.java
> +        return;
마지막 return은 굳이 안해줘도 되지 않을까요?

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/user/model/Reservation.java
> +        return true;
조건문 자체로 결과가 될 수 있지 않을까요?

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/user/model/WishList.java
> +    private boolean wish;
boolean형이 아니라 그냥 데이터의 유무로도 알 수 있을 것 같다는 생각이 드네요 ㅎㅎ

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/utils/CalcUtil.java
> +public class CalcUtil {
개인적으로 Fullname을 적어주시는게 좋을 것 같아요.

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/utils/CalcUtil.java
> +    }
잘 와닿지 않네요.
좀 더 남이 봤을 때 직관적으로 설계하는 시도를 해보면 좋을 것 같아요.

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/utils/DTOConverter.java
> +public class DTOConverter {
요건 없애는게 좋을 것 같네요.

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/utils/GetPropertyUtil.java
> +public class GetPropertyUtil {
그냥 PropertyUtil이었어도 상관없을 것 같아요.
그리고 뭔가 빠졌죠.

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/utils/GetPropertyUtil.java
> +public class GetPropertyUtil {
만약에 ApplicationContext가 필요했다면, 굳이 Util이어야 했나 싶네요.

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/utils/mapper/CityMapper.java
> +public class CityMapper implements RowMapper<City> {
람다식으로도 만들어줄 수 있고 Bean으로 관리해도 됩니다.
매 번 생성해 줄 필요는 없어요.

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/utils/sql/CitySQL.kt
> +const val FIND_ALL : String = """
IntelliJ는 주석이나 String을 code로 인식하는 기능을 이용하면 Code Completion등의 기능을지원해줍니다.

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/utils/sql/CitySQL.kt
> +
조건절이나 LIMIT 없이 사용은 지양해주세요.

2021-06-03 16:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/utils/sql/RoomSQL.kt
> +const val FIND_ALL_PRICE_BY_SEARCH_REQUIREMENT: String = """
이 파일 같이 일하는 동료가 짰다고 생각해보시면, 개선 포인트를 찾을 수 있지 않을까요?

2021-06-03 16:04 UTC, ksundong commented on backend/src/test/java/com/codesquad/coco/ReservationTest.java
> +    @DisplayName("날짜가 중간에 들어가는지")
좀 더 상세하게 적어주면 좋을 것 같네요.

2021-06-04 03:33 UTC, ChoiGiSung commented on backend/src/main/java/com/codesquad/coco/room/model/Room.java
> +    }
DTO에 로직을 추가하면 안되는 줄 알았는데, 찾아보니 간단한 값 변환이나 유효성 검사는 괜찮다고 해서 변경했습니다.
DTO에 숙박일을 계산하는 메소드를 추가해 줬습니다.


`capacityCheck`와 `reservationDateCheck`등은 실제로 밑에서 다음과 같이 동작합니다.

>     public boolean capacityCheck(int adult, int child) {
>         if (!roomOption.capacityCheck(adult, child)) {
>             throw new OvercapacityException();
>         }
>         return true;
>     }
> 
>     public boolean reservationDateCheck(LocalDate checkIn, LocalDate checkOut) {
>         for (Reservation reservation : reservations) {
>             if (!reservation.reservationDateCheck(checkIn, checkOut)) {
>                 throw new NonReservationException();
>             }
>         }
>         return true;
>     }

체크 같은 로직은 해당 객체에 위임하고, 그 로직을 행하는 메소드를 `room`객체에 정의되어있습니다.
`reservationAvailability`메소드에서 분리한 이유는 메소드가 길어지고, 메소드 하나에 하나의 책임을 가지게 하려는 목적이었습니다.

금액 계산 로직은 할인비용,추가비용 따로 계산되어야 할 것 같아서 2개의 메소드로 분리를 했었습니다.
이 부분도 위의 조언에 따라 하나의 메소드만 호출하게 변경했습니다.
39d4cd4

2021-06-04 04:02 UTC, ChoiGiSung commented on backend/build.gradle
> +    implementation files('build/libs/gitOauthV1.jar')
넵! 맞습니다. 저번 미션에 라이브러리로 만들어 보라는 옵션이 있어서 그 때 만들고 이번에 재사용을 해봤습니다.

2021-06-04 05:16 UTC, ChoiGiSung commented on backend/src/main/java/com/codesquad/coco/city/CitiesDTO.java
> +    private List<CityDTO> cities;
수정했습니다.

2021-06-04 05:35 UTC, ChoiGiSung commented on backend/src/main/java/com/codesquad/coco/city/CityDAO.java
> +@Component
Repository를 사용하지 않았던 이유는 DAO와 Repository는 같지 않다고 생각해서였습니다.
 dao는 table 하나에 해당하고, repository는 루트 애그리거트를 위한 것이기 때문입니다.

근데 이번에 찾아보니 프리젠테이션 레이어에서는 Repository를 사용하라고 하네요.
 다음부터는 repository를 사용하도록 하겠습니다.

2021-06-04 05:42 UTC, ChoiGiSung commented on backend/src/main/java/com/codesquad/coco/city/CityDTO.java
> +package com.codesquad.coco.city;
현재는 하나의 도메인 안에 관련된 것을 다 넣었는데, 
다음에는 계층 별로 패키징을 해보겠습니다.

2021-06-04 05:59 UTC, ChoiGiSung commented on backend/src/main/java/com/codesquad/coco/city/CityService.java
> +                .map(DTOConverter::cityToCityDTO)
하나의 메소드를 통과해서 공통적으로 처리하고 싶었는데. 변화에 쉽게 대응하지 못하겠네요.
컨버터를 삭제하고 각 DTO에서 정적 팩토리 메소드를 정의했습니다.

2021-06-04 06:12 UTC, ChoiGiSung commented on backend/src/main/java/com/codesquad/coco/global/ApplicationContextServe.java
> +public class ApplicationContextServe implements ApplicationContextAware {
이 부분은 최종적으로  `GitHubDeviceType`을 위해서 작성했습니다.

해당 class를 통해 `applicationContext`를 얻고, `GetPropertyUtil`에서 컨텍스트를 활용해서 `properties`를 읽으려 했습니다.

`GitHubDeviceType`에서 활용하는 부분입니다.

>     IOS("github.ios.client.id", "github.ios.secret", "http://localhost:8080/git/auth/app"),
>     DESKTOP("github.desktop.client.id", "github.desktop.secret", "http://localhost:8080/git/auth");
> 
>     GitHubDeviceType(String clientKey, String clientSecret, String redirectUri) {
>         this.clientKey = GetPropertyUtil.getProperty(clientKey);
>         this.clientSecret = GetPropertyUtil.getProperty(clientSecret);
>         this.redirectUri = redirectUri;
>     }

ios와 desktop을 구분 지은 이유는 각각 다른 app이기 때문입니다. 그렇기에 다른 `clientId`가 있습니다.
이렇게 구현한 이유는 `redirectUri ` 때문이었습니다. git은 하나의 redirectUri만 등록할 수 있더라고요.
어떻게 해결할까 하다가 인프런이 위와 같이 다른 app을 사용하는 것을 보고  코드로 구현해봤습니다.

이렇게 되면 사용자는 로그인 시에 device 타입만 바꾸면 다른 app으로 접속이 가능합니다.
```
    @PostMapping("/v1/auth/{gitHubDeviceType}")
    public JWT login(@RequestParam String code, @PathVariable GitHubDeviceType gitHubDeviceType) {
        GitUserInfoDTO userInfo = userService.loginByGitOauth(code, gitHubDeviceType);
        String jwt = JWTUtils.createJWTTypeBearer(userInfo, serverKey.getJwtServerKey());
        return new JWT(jwt);
    }
```

제가 궁금했던 점은 enum에서 직접 작성한 값을 생성자에서 활용해 초기화하는 부분이었습니다.
이렇게 구현 해본 적이 없어서 괜찮은 방법인지 아니면 복잡도만 증가한 것인지 고민입니다.

2021-06-04 06:14 UTC, ChoiGiSung commented on backend/src/main/java/com/codesquad/coco/global/exception/CustomExceptionHandler.java
> +
다 비슷한 주석이라 복붙하다 생긴 빈 줄 같네요. 수정했습니다!

2021-06-04 06:16 UTC, ChoiGiSung commented on backend/src/main/java/com/codesquad/coco/global/exception/CustomExceptionHandler.java
> +    @ExceptionHandler(OverTimeException.class)
맞습니다. jwt를 구현할 때 더 많은 예외를 잡았어야 했는데, 하나의 예외만 잡았습니다..
수정하게 된다면 jwt 예외를 상위로 두고 그것을 공통적으로 잡아처리하겠습니다.

2021-06-04 06:26 UTC, ChoiGiSung commented on backend/src/main/java/com/codesquad/coco/global/exception/CustomExceptionHandler.java
> +    @ResponseStatus(HttpStatus.FORBIDDEN)
401은 로그인되어 있지 않을 때
403은 권한이 없는 곳에 요청할 때라고 이해하고 있습니다.

overTime은 jwt가 만료된 것이기에 로그인이 안 돼 있다고 판단하고 401이 주는 게 좋을 거 같습니다.

2021-06-04 06:29 UTC, ChoiGiSung commented on backend/src/main/java/com/codesquad/coco/global/exception/ErrorCode.java
> +    INVALID_INPUT(404, "잘못된 입력"),
400으로 교체했습니다!

2021-06-04 06:37 UTC, ChoiGiSung commented on backend/src/main/java/com/codesquad/coco/global/exception/ErrorCode.java
> +    UNAUTHORIZED_JWT(404, "jwt를 확인 하세요"),
401로 수정했습니다!

2021-06-04 06:39 UTC, ChoiGiSung commented on backend/src/main/java/com/codesquad/coco/global/exception/ErrorCode.java
> +        this.message += valueOf;
message로 수정했습니다.

2021-06-04 06:41 UTC, ChoiGiSung commented on backend/src/main/java/com/codesquad/coco/global/exception/business/notfound/NotFoundRoomException.java
> +        super(ErrorCode.USER_NOT_FOUND);
수정했습니다!

2021-06-04 06:41 UTC, ChoiGiSung commented on backend/src/main/java/com/codesquad/coco/global/exception/business/notfound/NotFoundUser.java
> +public class NotFoundUser extends NotFoundException {
허허.. 개판이네요..

2021-06-04 06:48 UTC, ChoiGiSung commented on backend/src/main/java/com/codesquad/coco/image/Image.java
> +    private String type;
처음부터 enum으로 생각했어야 했는데, 왜 생각하지 못했을까요. 다음부터 적용하겠습니다.

2021-06-04 06:51 UTC, ChoiGiSung commented on backend/src/main/java/com/codesquad/coco/oauth/gitoauth/GitOauth.java
> +    public void changeType(GitHubDeviceType gitHubDeviceType) {
ios와 fe는 다른 clientId가 필요하기에 변경했습니다.
다른 방법으로는 각각 인스턴스를 만들어 사용할까도 생각해 봤지만 변경하는 비용이 더 적겠다고 생각해 이렇게 했습니다.

2021-06-04 07:04 UTC, ChoiGiSung commented on backend/src/main/java/com/codesquad/coco/oauth/gitoauth/GitOauth.java
> +public class GitOauth extends Oauth {
`accessToken`을 받는 부분이나 `userInfo`를 받는 부분은 기본 동작으로 서비스마다(git, google) 같다고 생각했습니다.  그래서 `Oauth `내부에서 `accessToken`과 `userInfo`를 얻는 부분을 구현했습니다.
근데 막상 구현하다 보니 `user`정보를 얻는 부분은 서비스마다 다를 수 있겠다고 판단을 했습니다. 그래서 `Oauth`에서 정의한 `userInfo`를 상속받는 `GitUserInfo`를 만들어 받는 식으로 처리했습니다.

2021-06-04 07:07 UTC, ChoiGiSung commented on backend/src/main/java/com/codesquad/coco/room/RoomController.java
> +    @GetMapping("/search/prices")
구글 검색 uri가 search를 사용하길래 따라했습니다.

2021-06-04 07:12 UTC, ChoiGiSung commented on backend/src/main/java/com/codesquad/coco/room/RoomDAO.java
> +    private ImageDAO imageDAO;
이 부분은 밑의 n+1 부분과 같은 이유입니다.
room을 부를 때 완벽하게 다 가지고 오려 했습니다.
한 번에 다 가지고 오면 java코드에서는 이 메소드를 통해 어느 곳에서든 알맞게 사용할 수 있겠다고 생각했습니다.
생각해보니 DAO인데 Repository를 흉내 내고 있지 않나 생각이 드네요.

2021-06-04 07:12 UTC, ChoiGiSung commented on backend/src/main/java/com/codesquad/coco/room/model/AdditionalCost.java
> +public class AdditionalCost {
감사합니다!

2021-06-04 07:15 UTC, ChoiGiSung commented on backend/src/main/java/com/codesquad/coco/room/model/Guest.java
> +        baby = baby != null ? baby : 0;
앗. 그렇겠네요. priceMin,Max와 함께 처리하다 보니 안 해도 되는 곳에 해놨네요.
수정했습니다.

2021-06-04 07:22 UTC, ChoiGiSung commented on backend/src/main/java/com/codesquad/coco/room/model/Location.java
> +    private City city;
음. 현재는 어디서도 사용하지는 않지만 db와 맞춰주려는 의도였습니다.  location이 city를 외래키로 가지고 있어서 객체로 구현해봤습니다.

2021-06-04 07:26 UTC, ChoiGiSung commented on backend/src/main/java/com/codesquad/coco/room/model/Location.java
> +    private double longitude;
Coordinates라는 VO를 만들었습니다. 
의미 전달이 더 좋아졌습니다!

2021-06-04 07:57 UTC, ChoiGiSung commented on backend/src/main/java/com/codesquad/coco/room/model/Review.java
> +    private double review;
리뷰는 구현하지 않기로 해서 모양만 만들었습니다.

2021-06-04 09:30 UTC, ChoiGiSung commented on backend/src/main/java/com/codesquad/coco/room/model/Money.java
> +    }
이 부분은 검색 조건이 null로 들어올 때 default 값을 같게 하려 했던 부분입니다.
Integer를 사용한 이유도 null 체크를 하기 위함이었습니다.
int로 했을 때 minPrice는 0이 들어와도 0으로 처리하면 되지만 maxPrice는 0으로 들어오면 0으로 처리해주고 null이면 조건을 안 적었다는 것이니 default인 max값을 주기 위함이었는데 좀 이상한가요?...

2021-06-04 09:36 UTC, ChoiGiSung commented on backend/src/test/java/com/codesquad/coco/ReservationTest.java
> +        Room room = getRoom();
그러게요.. 저도 값을 한 번 더 확인하게 되네요.

2021-06-04 09:37 UTC, ChoiGiSung commented on backend/src/main/java/com/codesquad/coco/room/model/dto/SearchPriceDTO.java
> +    @ConstructorProperties({"check-in", "check-out", "city-name"})
하이픈으로 받을 때 문제가 좀 있더라고요.
그래서 해당 방법을 찾아서 적용했습니다.

2021-06-04 09:48 UTC, ChoiGiSung commented on backend/src/main/java/com/codesquad/coco/room/model/dto/SearchRoomDTO.java
> +    @ConstructorProperties({"check-in", "check-out", "city-name", "adult", "child", "baby", "price-min", "price-max"})
컨트롤러에서 다형성을 이용하지 않고 있어서 각각 만들어 줬습니다.
값이 들어오는 것을 다형성으로 처리하는 방법을 모르겠어서 놓고 있었습니다.

2021-06-04 13:06 UTC, ChoiGiSung commented on backend/src/main/java/com/codesquad/coco/room/model/dto/SearchRoomDTO.java
> +public class SearchRoomDTO extends SearchPriceDTO {
controller에서 사용하기에 쉽지 않을 것 같습니다
Search를 최상위로 두고 다형성을 controller에 적용 시켜 보려 했는데, 타입을 명시하지 않는 한 불가능하다는 글을 봤습니다.
https://stackoverflow.com/questions/42965921/use-interface-in-spring-controller-method-argument

2021-06-04 13:23 UTC, ChoiGiSung commented on backend/src/main/java/com/codesquad/coco/user/model/Reservation.java
> +        return true;
수정했습니다!

2021-06-04 13:42 UTC, ChoiGiSung commented on backend/src/main/java/com/codesquad/coco/utils/CalcUtil.java
> +    }
bat도 계속 말해줬던 부분인데, 소수점으로 저장하고 바로 곱하는 게 맞을 거 같습니다.

2021-06-04 13:42 UTC, ChoiGiSung commented on backend/src/main/java/com/codesquad/coco/utils/DTOConverter.java
> +public class DTOConverter {
삭제했습니다!

2021-06-04 13:43 UTC, ChoiGiSung commented on backend/src/main/java/com/codesquad/coco/utils/GetPropertyUtil.java
> +public class GetPropertyUtil {
private된 생성자를 추가해줬습니다. 음 util말고는 딱히 이름이 떠오르지 않아서 지었습니다.

2021-06-04 14:14 UTC, ChoiGiSung commented on backend/src/main/java/com/codesquad/coco/utils/sql/CitySQL.kt
> +
10개로 제한했습니다!

2021-06-04 14:25 UTC, ChoiGiSung commented on backend/src/main/java/com/codesquad/coco/utils/sql/RoomSQL.kt
> +const val FIND_ALL_PRICE_BY_SEARCH_REQUIREMENT: String = """
몇개를 다른 sql로 이동시켰습니다!

2021-06-05 05:58 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/city/CityDAO.java
> +@Component
프리젠테이션 레이어가 아니라 퍼시스턴트 레이어일겁니다 ㅎㅎ 착각하신 것 같아요.
코코가 말씀하시는 Repository라는 용어는 DDD의 용어입니다.
거기의 영향을 받은게 Spring Data의 Repository들이죠.
Repository 애노테이션은 그 의미는 없는 것 같아서 DAO에 사용해주시면 될 것 같고, DAO 역시 table 하나에 해당되지 않는다고 생각해요. (만약 하나만 담당해야한다면 조인을 쓰면 안되겠죠?)

2021-06-05 06:01 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/global/ApplicationContextServe.java
> +public class ApplicationContextServe implements ApplicationContextAware {
애플리케이션 컨텍스트를 클래스 레벨에서 읽으려 하는 것 부터 위험하다고 생각되긴 하네요.
JVM의 동작원리와 Spring이 어떻게 동작하는지에 대해서 안다면 아마 다른 접근 방법을 취하지 않을까 싶어요.
사실 디바이스 타입을 직접 넘겨주는 것 자체가, 그렇게 좋은 설계인가? 에 대해서 생각해보시면 좋을 것 같아요.
왜 타입별로 구분이 필요할까요?

2021-06-05 06:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/oauth/gitoauth/GitOauth.java
> +public class GitOauth extends Oauth {
구현이 다르다면 그냥 인터페이스만 두고 구현상속은 하지 않는 방향을 추천드릴게요.

2021-06-05 06:03 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/oauth/gitoauth/GitOauth.java
> +public class GitOauth extends Oauth {
결국 부모클래스에 구현이 묶여버리는 설계가 나와서 추천드리지 않아요.

2021-06-05 06:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/oauth/gitoauth/GitOauth.java
> +    public void changeType(GitHubDeviceType gitHubDeviceType) {
저는 이 부분이 잘 이해가 안가요 왜 다른 clientId가 필요한가용??

2021-06-05 06:06 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/room/RoomController.java
> +    @GetMapping("/search/prices")
사실 구글 검색의 경우에는 RESTful 하다고 표방하지 않는 만큼 참고하시면 힘들것 같네요.

2021-06-05 06:07 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/room/RoomDAO.java
> +    private ImageDAO imageDAO;
Repository와는 다르게, Repository 안에 Repository같은 형태로 구성되어있는 것 같은데요~
그냥 테이블을 조인해오면 안됐을까요?

2021-06-05 06:08 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/room/model/Location.java
> +    private City city;
latitude와 longitude를 같이 다니게끔 해주면 어떨까요?

2021-06-05 06:08 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/room/model/Location.java
> +    private City city;
그렇군요.

2021-06-05 06:10 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/room/model/Money.java
> +    }
money를 null을 안받아주면 되지 않을까요?
MYSQL에는 null일 때 지정된 값을 넣을 수 있는 Function도 있습니다.

2021-06-05 06:10 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/room/model/dto/SearchPriceDTO.java
> +    @ConstructorProperties({"check-in", "check-out", "city-name"})
어디에서 나온 내용일까요?
케밥케이스의 사용은 처음 듣는 얘기네요.

2021-06-05 06:13 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/room/model/dto/SearchRoomDTO.java
> +public class SearchRoomDTO extends SearchPriceDTO {
이런 문제가 있었군요.. 제 리뷰는 무시하셔도 괜찮을 것 같습니다~

2021-06-05 06:13 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/room/model/dto/SearchRoomDTO.java
> +    @ConstructorProperties({"check-in", "check-out", "city-name", "adult", "child", "baby", "price-min", "price-max"})
다형성의 문제는 아닌 것 같은데 케밥케이스여서 생기는 문제같아요.

2021-06-05 06:13 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/utils/CalcUtil.java
> +    }
네이밍도 좀 더 생각해보시면 좋을 것 같아요.

2021-06-05 06:14 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/utils/sql/RoomSQL.kt
> +const val FIND_ALL_PRICE_BY_SEARCH_REQUIREMENT: String = """
그것 말고도 SQL이 엄청 읽기 힘들었을 것 같아요~

2021-06-05 06:15 UTC, ksundong approved these changes
피드백 반영하고 적용하시느라 고생하셨습니다~

2021-06-05 06:15 UTC, merged

2021-06-05 08:28 UTC, ChoiGiSung commented on backend/src/main/java/com/codesquad/coco/oauth/gitoauth/GitOauth.java
> +    public void changeType(GitHubDeviceType gitHubDeviceType) {
ios측과 fe측이 code를 받을 redirectUri가 다르기 때문입니다.

fe측만 있을 경우는 localhost:3000을 redirectUri로 해버리면 됐었는데,
ios도 같이 협업하게 되어서 localhost:3000으로 등록을 해버리면 code를 받을 수 없더라고요.
git oauth app은 하나의 redirectUri만 등록 가능한 게 문제의 원인입니다.

(이게 아니라면 redirectUri를 서버 쪽으로 해서 처리하는 방식이 있을 것으로 생각합니다.
ios와 fe로 가기 전에 중간 page를 만들어 버튼 형식으로 각각 전달하는?
이는 구현해 보지 않아서 가능한지는 잘 모르겠네요.)

그래서 생각한 점이 2개의 app을 만들어 각각 관리하자 였습니다.
이런 생각을 한 이유는 인프런 서비스가 
[안드로이드](https://user-images.githubusercontent.com/60220562/120885250-e9e1a900-c622-11eb-9274-c4f10b4a7ab6.png)
[브라우저](https://user-images.githubusercontent.com/60220562/120885256-eea65d00-c622-11eb-8ea9-d872d3b6dee3.png)
각각 다른 app을 쓰고 있기에 이것을 보고 따라하게 되었습니다.

git로그인이 가능한 서비스는 더 못찾아서 인프런만 모티브로 하였는데, 다른 서비스에서는 어떻게 풀어가는지 궁금하기도 합니다.

2021-06-05 08:32 UTC, ChoiGiSung commented on backend/src/main/java/com/codesquad/coco/global/ApplicationContextServe.java
> +public class ApplicationContextServe implements ApplicationContextAware {
타입 구분이 필요한 이유는 밑의 client Id가 왜 달라야 하는가 에서 설명하겠습니다.

2021-06-05 08:39 UTC, ChoiGiSung commented on backend/src/main/java/com/codesquad/coco/room/RoomDAO.java
> +    private ImageDAO imageDAO;
일대다로 구현되어 있어서(방이 일, 이미지가 다) 썸네일 한 장만 가지고 오지 않는 이상 조인 시 방 정보가 중복으로 오지 않나요? 
그래서 방 가져오는 쿼리, 이미지 전부 가지고 오는 쿼리를 짰습니다.

2021-06-05 08:42 UTC, ChoiGiSung commented on backend/src/main/java/com/codesquad/coco/room/model/Money.java
> +    }
처음 fe와 ios 분들과 이야기 할 때 null 값도 받아 주기로 했습니다.
이 부분은 검색할 때 검색 조건을 다 입력하지 않아도 검색이 되게 하기 위함이었는데요.

처음 부터 동적 쿼리를 썼다면 이런 식으로 풀지 않았을 텐데 이 부분은 좀 아쉬웠습니다.

2021-06-05 08:47 UTC, ChoiGiSung commented on backend/src/main/java/com/codesquad/coco/room/model/dto/SearchPriceDTO.java
> +    @ConstructorProperties({"check-in", "check-out", "city-name"})
https://stackoverflow.com/questions/10302179/hyphen-underscore-or-camelcase-as-word-delimiter-in-uris 
https://specs.openstack.org/openstack/api-wg/guidelines/naming.html

혹시 제가 이해를 잘못한 것일까요? 구글 번역의 힘으로는 하이픈을 사용하라고 이해를 했습니다.

2021-06-05 08:49 UTC, ChoiGiSung commented
감사합니다 디온.
몇몇 부분에 확신이 없었는데 도움이 되었습니다.
client id에 관한 부분은 다시 코멘트를 달아놨습니다.

2021-11-21 13:07 UTC, ksundong commented on backend/src/main/java/com/codesquad/coco/room/model/dto/SearchPriceDTO.java
> +    @ConstructorProperties({"check-in", "check-out", "city-name"})
@ChoiGiSung 
제가 다시 리뷰를 보고 있는데 답변을 안달아서 답변 달아드립니다.
리소스에는 하이픈을 달아주는 것이 맞지만
응답 필드에서는 정해진 규칙은 없고 일반적으로 snake case를 많이씁니다. 정하기 나름이라 camel case도 많이쓰고, kebab case는 처음보는 형태이긴 했어요.