[TEAM-16 (Jane)] 기본 기능 + OAuth 구현 후 PR드립니다.
codesquad-members-2021/airbnb pull request #70
Opened 2021-06-01 21:07 UTC by janeljs

안녕하세요! 16팀 백엔드를 담당하고 있는 Jane입니다🙂
기본 기능 및 OAuth 로그인 구현이 완료되어 PR을 드립니다. 이번에는 일주일에 두 번씩 PR을 드리고 싶었는데 결국 마지막 주차에 PR을 드리게 되었네요😢

코드스쿼드에서 진행하는 프로젝트가 2건밖에 남지 않았고, 이번 프로젝트를 마감에 맞춰 JPA 프로젝트를 포폴로 지원하고 싶은 곳이 있어서 Spring Data JPA + Querydsl을 사용하여 구현하였습니다! Querydsl도 처음써보고, JPA도 쉬울줄 알았지만 삽질의 연속이어서 구현하는데 생각보다 오랜 시간이 걸렸습니다.

### 구현한 기능
- 기본 페이지 조회
- 필터링된 방 조회
- 상세 페이지 조회
- OAuth 로그인
- 예약하기 및 예약 취소
- 위시리스트 추가 및 삭제
- 위시리스트 조회

### 구현 못한 기능
- Elastic Search를 이용한 검색
- 요금별 숙소 분포도
- 페이징 처리

### 배포
- EC2, VPC, RDS, S3, Nginx, crontab 등을 사용하여 배포
- 프론트 코드 배포 완료
- Github action 적용 x

### 기타
1. ResponseEntity를 안 써도 되는 상황이면 사용하지 않는 것이 좋다는 리뷰를 본 적이 있어 제거하였습니다.
2. path variable과 query string 각각 어느 상황에 쓰면 좋을지 궁금해요! query string은 필터링할 때, path variable은 정확한 항목을 조회할 때 쓰면 될까요?
3. OAuth를 구현할 때 프론트로부터 코드를 받는게 아니라 콜백 url에서 직접 authorization code를 받아온 뒤, RedirectView를 통해 redirect해줄 때 쿼리 파라미터로 jwt 토큰과 profile_url을 함께 보내주고 있는데, 이런식의 구현도 괜찮은건지 궁금합니다!
4. 클래스는 작게 쪼개져있지만, embedded 타입이 많아 room이 엄청 비대해졌는데, entity로 더 분리했어야 하는지 궁금해요👀 얼핏 db 테이블은 객체랑 다르고 커도 괜찮다는 말을 들었던 것 같은데 조언주시면 감사하겠습니다ㅎㅎ

부족한 코드, 소중한 시간을 내어 리뷰해주셔서 감사합니다🙇‍♀️

2021-06-05 06:19 UTC, wheejuni requested changes
수고 많으셨습니다 👍 💯

2021-06-05 06:19 UTC, wheejuni commented on BE/airbnb/src/main/java/airbnb/auth/AuthService.java
> +        return webClient.post()
여기 사이에 한 줄 띄우면 좋겠네요.

2021-06-05 06:19 UTC, wheejuni commented on BE/airbnb/src/main/java/airbnb/auth/AuthService.java
> +                .header("Authorization", "token " + accessToken)
`HttpHeaders` 적용해봅시다!

2021-06-05 06:19 UTC, wheejuni commented on BE/airbnb/src/main/java/airbnb/auth/GithubArgumentResolver.java
> +        return parameter.getParameterAnnotation(Github.class) != null;
`.hasAnnotation()` 사용해주세요!

2021-06-05 06:19 UTC, wheejuni commented on BE/airbnb/src/main/java/airbnb/auth/GithubUser.java
> +    public static User createUser(GithubUser githubUser) {
`static` 이 꼭 필요한가요?
객체 자기자신을 `User` 로 변환하는 로직만 구현되면 충분하지 않을까요?

2021-06-05 06:19 UTC, wheejuni commented on BE/airbnb/src/main/java/airbnb/auth/jwt/JwtAuthInterceptor.java
> +        Jwt jwt = new Jwt(header.substring("Bearer".length()).trim());
길이 기준 substring보다는 `"Bearer "`  를 기준으로 `.split()`  하는게 더 안전하진 않을까요?

2021-06-05 06:19 UTC, wheejuni commented on BE/airbnb/src/main/java/airbnb/controller/BookingController.java
> +        return bookingService.reserve(user, room, reservationInfo);
`BookingService` 에서 객실까지 찾으면 안되나요?

2021-06-05 06:19 UTC, wheejuni commented on BE/airbnb/src/main/java/airbnb/controller/HomeController.java
> +    private final CategoryRepository categoryRepository;
별도의 `Service` 가 설계돼야겠죠?

2021-06-05 06:19 UTC, wheejuni commented on BE/airbnb/src/main/java/airbnb/controller/HomeController.java
> +        return new HomeResponse(nearbyDestinations, liveAnywhere);
홈화면에 필요한 정보를 만들어주는 다른 클래스를 설계해주세요!

2021-06-05 06:19 UTC, wheejuni commented on BE/airbnb/src/main/java/airbnb/controller/HomeController.java
> +    public Map<Integer, Integer> getPriceDistribution() {
별도의 DTO를 설계해 보시구요.

2021-06-05 06:19 UTC, wheejuni commented on BE/airbnb/src/main/java/airbnb/controller/HomeController.java
> +        }
이 로직도 분리를 해주시면 좋겠어요.

2021-06-05 06:19 UTC, wheejuni commented on BE/airbnb/src/main/java/airbnb/response/CityResponse.java
> +@AllArgsConstructor
위험합니다!

2021-06-05 06:19 UTC, wheejuni commented on BE/airbnb/src/main/java/airbnb/service/UserService.java
> +        }
`User` 로 메소드를 이동시켜서 유저 클래스에게 책임을 부여하는게 좋지 않을까요?

2021-06-05 08:01 UTC, janeljs commented on BE/airbnb/src/main/java/airbnb/auth/GithubUser.java
> +    public static User createUser(GithubUser githubUser) {
말씀주신대로 수정했습니다!😃

2021-06-05 08:02 UTC, janeljs commented on BE/airbnb/src/main/java/airbnb/controller/HomeController.java
> +        return new HomeResponse(nearbyDestinations, liveAnywhere);
요금 분포도 값을 담고있는 클래스를 추가하였습니다.

2021-06-05 08:03 UTC, janeljs commented on BE/airbnb/src/main/java/airbnb/service/UserService.java
> +        }
User로 메서드를 이동하였습니다!

2021-06-07 02:38 UTC, janeljs commented
@wheejuni 코드리뷰 반영했습니다! 확인 후 이상 없다면 머지부탁드려요🙂

2021-06-07 08:27 UTC, merged